---
title: |
  | Chapter 5
  | Synthesis and Conclusions
author: ""
date: ""
output:
  word_document:
    reference_docx: manuscriptstyle_thesis.docx
  pdf_document: default
  html_document:
    number_sections: yes
csl: tree-physiology.csl
bibliography: references.bib
---

```{r, results="asis", echo=FALSE, warning=FALSE}
library(knitr)
opts_knit$set(root.dir = '../')
```

#5.1  Synthesis
It has long been recognized that resources limit plant growth in different environments, at different life stages and individual plant processes are limited by different resources [@bazzaz2000reproductive]. Consequently, a quantitative understanding of how plants gain and allocate resources is necessary to predict their success in any environment [@mooney1972carbon]. In this thesis, resources allocated for growth in *Eucalyptus* tree species are classified into two distinct groups. The first group consists of environmental plant resources, such as N and H~2~O, that are captured, distributed and utilized to drive rates of leaf photosynthesis (*A~n~*) and thus tree C gain. These C assimilates comprise the second group, which are the essential internal resource required for tissue growth, storage and to fuel respiration. These two resource groups are inextricably linked and interact to define plant growth across spatial and temporal scales. For example, the C expended in acquiring N makes up a significant fraction of the total energy a plant consumes, while leaf N investment constrains photosynthetic capacity [@chapin1987plant]. In trees, rates of *A~n~* will then depend on the photosynthetic light response of individual leaves and the energetic trade-offs of gas exchange related to transpiration and water supply [@givnish1988adaptation].

\
The research presented in this thesis was designed to investigate resource allocation in trees at individual tissue and whole plant scales in *Eucalyptus*. I sought to address theories of plant functional balance by testing biomass partitioning in seedlings and trees undergoing various environmental manipulations. As observed biomass production may not necessarily reveal shifts in plant functional responses to environmental change, I evaluated the sensitivity of the allocation of photosynthate above and belowground across different temporal scales. Using mass balance approaches I then tested the coordination between growth and *A~n~*, using leaf gas exchange parameters in seedlings and measurements of net canopy C gain in trees. To help bridge the knowledge gap between leaf and canopy C gain I investigated the distribution of N and H~2~O as a function of light availability within canopies and the effect this has on individual leaf physiology. By utilizing novel experimental approaches, evidence from this work improves our understanding of functional processes that determine the net C uptake of trees and then how this assimilated C is used to fuel growth. The contribution of this body of work provides fundamental evidence underlying resource allocation in ecologically and commercially important *Eucalyptus* tree species.

##5.1.1 Where does the carbon go?
This thesis question arises from large uncertainties that remain regarding fundamental processes which affect terrestrial C cycling.  The question “Where does the carbon go?” arises from the need to track the fate of C from canopy *A~n~* to determine the contribution of forests ecosystems to C cycling [@litton2007carbon]. Currently, empirical data on C allocation are critical to the further development of forest models and subsequent predictions of global C balance under climate change [@franklin2012modeling]. Growth responses during early phases of tree establishment (seedlings or young trees) to changes in soil resource availability or climate change factors will likely depend on shifts in the plant C budget to balance growth, respiration and storage. Consequently, understanding environmentally driven shifts in C allocation in young *Eucalyptus* trees will be crucial to manage their fitness in fragile native ecosystems and their productivity in terms of timber production and quality in forestry systems.

\
First, I examined patterns in biomass partitioning of *E.tereticornis* seedlings with belowground resource limitation (Chapter 1) and with *E.saligna* trees exposed to eC~a~ and drought treatments (Chapter 2). Across these studies, partitioning of biomass largely followed allometric trajectories related to plant size, nearly independent of treatment manipulation. Partitioning to roots, leaves and stems in *E.tereticornis* seedlings was conserved across a ten-fold variation in seedling biomass with and without soil volume restriction. During this early growth stage, these results infer that growth inhibition from reduced belowground sink strength did not elicit a functional partitioning response. With much larger 2 year old *E.saligna* trees, grown in WTCs, differences in partitioning to stem biomass were detected between aC~a~ and eC~a~ treatments. These patterns were also attributed to size dependent relationships associated with ontogeny [see @poorter2015does], rather than a direct functional response to eC~a~.

\
Combined results from these two experiments argue against traditional views of plant functional balance in the context of observed biomass production. These theories posit that plants will “optimally forage” for the most limiting resource, thus shifts in biomass partitioning should occur. However, adaptive plant responses may not include changes in biomass production at any given “snapshot” in time.  This makes tracking C allocation to processes other than observed biomass just as important in assessing overall responses to manipulations of resource availability. Here, empirical and modelling evidence from Chapters 2 & 4 reveal that detection in shifts of tissue C allocation were necessary to interpret whole tree response to environmental manipulations. For *E.tereticornis* seedlings, modelling results infer that increases in C allocation to pools other than biomass were required to fully explain the effects of soil volume restriction on seedling growth. For *E.saligna* trees, increased leaf C demand under eC~a~ treatments resulted in higher C allocation to leaves without altering observed leaf biomass production. Overall, the ability to distinguish biomass production from C allocation across tissues reveals that alternate explanations are likely need to interpret the degree in which trees strive to maintain functional balance.

\
Alternatively, shifts in tissue morphology, metabolism or turnover to alter resource uptake of loss [@reich2002root], increased root exudation to alleviate resource limitation [@phillips2011enhanced] or increased C allocation to storage [@sala2012carbon ; @dietze2014nonstructural] may be used to balance trade-offs between tissue sink strength, resource availability and source C supply. Partial evidence for these ‘non-biomass’ responses were evident in *E.tereticornis* seedlings in research presented in Chapter 2. Increases in specific root length were detected in some, but not all, of seedlings with soil volume restriction. Modelling results also revealed that increases in tissue respiration rates were a possible mechanism to account for the oversupply of C not allocated to biomass. Increases in leaf carbohydrate storage were correlated with reduced belowground sink strength in these seedlings, and it is possible that C storage increased in other tissues. Although not measured, root exudation may have increased in response to adverse poor quality soil conditions with *E.tereticornis* seedlings in containers or in *E.saligna* trees under eC~a~ to meet resource demand.

\
The ability to compare biomass partitioning with aspects of C allocation across multiple experiments highlights how partial accounting of C may lead to erroneous conclusions regarding adaptive plant responses to changing environments. Overall, these results reveal why studies using only biomass partitioning to assess functional balance or allometric based theories have mixed results. Additionally, shifts in above but not belowground C allocation *E.saligna* trees disagrees with the common observation of enhancement of belowground processes in other trees species under eC~a~ [see @palmroth2006aboveground; @iversen2014terrestrial]. Shipley et al. [-@shipley2002balanced] states that it is more appropriate to state that plants shift biomass allocation to reduce imbalances between leaf source activity and tissue resource acquisition. Collectively, results from this research tend to agree with this conclusion, with the caveat that the concept of allocation must be extended to include fates of C other than measured biomass. Consequently, we agree with Poorter et al. [-@poorter2012biomass] that understanding C allocation above and belowground requires a better understanding of the interactions between tissue source and sink activity at any time point. In order to fully understand the impact environmental change has on forest productivity approaches to quantify patterns in C allocation must be prioritized in future studies.

##5.1.2 When do photosynthesis and growth not add up?

This thesis question addresses the debate over how strongly plant growth is controlled by either source or sink activity, which may disrupt the coordination between *A~n~* and growth at different temporal scales. Assimilated C is first allocated to provide sufficient sugars for the immediate demands of the plant during the day, and sufficient starch to meet ‘anticipated’ demands during the following night [@smith2007coordination]. The C demands for each tissue, referred to as tissue C sinks, determine the C budget for the entire plant and regulate C allocation. Despite competition among highly integrated C sinks, woody plants also maintain storage carbohydrate pools as C reserves [@kozlowski1992carbohydrate]. Understanding the coordination between plant growth and *A~n~* thus requires mass balance approaches to quantify the fractions of C supply allocated to growth, storage and respiration of different organs. Reductions in tissue sink strength have been shown to signal the down regulation of *A~n~*, which can led to increased starch synthesis for storage [@sage1994acclimation; @kitao2007interaction]. This had led to support for the argument that increased shifts to C storage will compete with C available for plant growth [@chapin1990ecology], which may then disrupt the coordination between *A~n~* and growth at short time scales.

\
To address this thesis question the belowground sink strength of *E.tereticornis* seedlings was manipulated, through container size treatments, to test the effects of putative sink limitation on *A~n~* and leaf TNC production (Chapter 1). Empirical results and modelling approaches were combined to test the coordination of A and growth of seedlings with and without soil volume limitation over 120 days. First, apparent reductions in belowground sink strength negatively impacted leaf N content and photosynthetic capacity, while leaf starch increased. These results support other findings where manipulation of tissue C sinks leads to carbohydrate accumulation and photosynthetic down regulation [@hoch2002altitudinal; @iglesias2002regulation; @equiza2006photosynthetic; @urban2007girdling; @haouari2013fruit]. Second, large reductions of harvested biomass in seedlings with soil volume limitation initially suggested that observed reductions in *A~n~* and growth were tightly linked. As previously shown in thesis Question 1, however, partial accounting of C allocation could lead to premature conclusions regarding this linkage. Importantly, using measured reductions in *A~n~* with a mass balance seedling growth model largely over-predicted biomass production from observed results. These findings reveal that not only can *A~n~* and growth not add up when belowground sink strength changes but other mechanisms, beyond *A~n~* and carbohydrate accumulation, must now be explored to explain growth responses.

\
At long enough time scales, however, *A~n~* and respiratory losses together determine net C balance and must be coordinated to plant growth. Consequently, we need to evaluate if trade-offs between storage and growth actually matter for long term C balance of trees [@palacio2014does]. The difficulty in measuring total canopy C uptake and the allocation of this assimilate to different tissue sinks currently impedes the ability to quantify whole tree C balance through time. Combining allometric approaches to estimate growth with seasonal variation in carbohydrates of stem wood and roots, Genet et al. [-@genet2010age] found contrasting results with the C balance between storage and growth across a chronosequence of stand age. Utilizing the novel WTC experimental design, I sought to address this knowledge gap by applying a simple mass balance approach with *E.saligna* trees (Chapter 4). Empirical measurements of net cumulative C uptake were correlated with whole tree C mass, which integrates the total allocation of C to growth and storage over an 11 month period. This simplified method allows for the coordination of *A~n~* and growth to be tested with minimal issues in accounting for C retention in tissues through time. During this time period, total tree C mass was strongly correlated to net canopy photosynthetic C gain across a 2.5 fold range in tree size. Even though the the C balance between growth and storage was likely disrupted by eC~a~ in these trees, it did not affect the overall coordination between C supply and growth over ~1 yr. Overall, results from Chapters 2 & 4 highlight how utilization of C mass balance improves our ability to explore mechanisms in which source and sink activity feedback to tree growth. Although I show that answers to the debate regarding the coordination of allocation of C to storage and growth requires a deeper understanding C allocation, it appears that whole canopy assimilation and tree growth are tightly coordinated over long periods.

##5.1.3  Are whole canopies optimized for carbon gain?

Scaling from single leaf photosynthetic performance to net canopy assimilation is difficult because of concomitant variations in environment and foliage physiology and structure [@niinemets2009packing]. The ability to estimate whole canopy C gain involves knowledge of the non-linear responses of *A~n~* to light between shaded and sunlit leaves [@de1997simple; @linderson2012up], which requires the ability to differentiate  light energy utilization, environmental resource distribution, physiological behavior and CO~2~ fluxes within tree canopies [@dai2004two; @peltoniemi2012co; @niinemets2012optimization]. Theory suggests that interactions between traits which influence *A~n~* and transpiration should interact to determine optimal patterns of behavior for whole plant C gain [@givnish1988adaptation]. Theories of optimal resource allocation and leaf physiological behavior have been developed [@cowan1977stomatal; @medlyn2011reconciling; @peltoniemi2012co] and subsequently tested [@wright2003least; @heroult2013optimal; @prentice2014balancing; @lin2015optimal] across different ecosystems and plant functional types. This thesis question arises because optimal leaf physiology is commonly assessed for seedlings or ‘full sun’ leaves, thus our understanding of how resource allocation and individual leaf physiology interact to maximize net canopy C uptake is surprisingly limited. Seeking answers to ecological questions such as “Where does the carbon go?” and “When do photosynthesis and growth not add up?” first requires an understanding of "Where is the carbon fixed?".

\
Theories of leaf economic strategies are often used to describe the patterns in which resources are distributed in order for plants to optimize *A~n~* [@wright2003least].  In this economic framework, I first evaluated how N and water supply were distributed in relation to photosynthetic capacity within *E. tereticornis* tree canopies (Chapter 3). Leaf N and photosynthetic capacity were found to be highest in full sun leaves, which agree with conventional theory that resources for *A~n~* should be preferentially invested relative to light availability. Overall, higher measured rates of *A~n~* in full sun leaves compared to shade leaves implies that N resources were invested to maximize source activity in upper canopy full sun leaves. The distribution of leaf hydraulic conductance, however, was not correlated with canopy N gradients or *A~n~* between sun and shade leaves. It was therefore necessary to further investigate relationships between leaf physiology, carbon uptake and water-use efficiency (WUE) across leaf types.

\
It has been previously hypothesized that stomatal conductance (g~s~) should be distributed within a canopy to utilize supplies of light, N and water to maximize *A~n~* [@peltoniemi2012co]. Under ambient light conditions g~s~ was consistently higher in shade leaves despite lower rates of *A~n~*. The resultant inefficient water use in shade leaves suggests that stomatal behavior may be optimized differently within tree canopies. Pearcy and Way [-@pearcy2012two] theorize that shade leaves may have mechanisms to enhance sunfleck use, including changes in induction through enzyme regulation or stomatal opening. Our data agree with Tausz et al. [-@tausz2005dynamic] that sustaining higher g~s~ may be a strategy to efficiently utilize sunflecks through reduced stomatal response time. This strategy, however, does not guarantee increased leaf C uptake as mesophyll conductance (g~m~) may still limit *A~n~*. Under high light conditions g~m~ and *A~n~* responded rapidly in shade leaves, leading to leaf C gain of greater magnitude than sun leaves. Rarely have relationships between *A~n~* and both g~s~ and g~m~ been quantified within tree canopies, thus I reveal a possible new mechanism of how leaf physiological behavior responds to light. These findings show that resources may also be distributed within a canopy to utilize sunflecks and that both CO~2~ resistance pathways must be accounted for when evaluating leaf behavior to optimize canopy C gain.

#5.2  Conclusions

##5.2.1 General conclusions
The diversity and non-linearity of plant ecophysiological processes poses challenges in predicting and analyzing structure and function of ecological systems [@field1983allocating]. These processes include complex strategies in ways plant uptake, distribute and utilize resources for growth in fluctuating environments. I examined how these resources, in the context of external environmental resources and new C assimilate, are allocated to fuel growth in both current and future climate conditions. This thesis work demonstrates that quantifying the underlying processes defining tree growth requires knowledge of the feedbacks between leaf source activity and tissue sink strength, which are both constrained by resource availability.  When addressing the fates of assimilated C across multiple experiments it was determined that biomass partitioning patterns did not support theories of “optimal foraging” when faced with eC~a~, drought, or belowground resource limitation. If trees strive to maintain functional balance, this collective research indicates that quantifying shifts in C allocation beyond biomass production are the key to unraveling adaptive responses. Additionally, I show how measuring shifts in C allocation are now necessary to gain new perspective regarding sink and source controls of growth and *A~n~*. This thesis research advocates for continued use of C mass balance approaches which include empirically measured or accurately modeled whole plant net C uptake. As this research presents new strategies in which tree canopies are optimized for C gain, further investigation of resource allocation and leaf physiological behavior within canopies should be prioritized to advance predictions of tree C gain. It will be the ability to quantify cumulative plant C gain through time combined with continued exploration of the fate of assimilated C that will allow future research to elucidate plant responses to environmental change beyond “snapshots” in time.

##5.2.2 *Eucalyptus* forests
A goal of this thesis was to contribute to the knowledge of the physiological ecology of *Eucalyptus* tree species to aid in understanding the susceptibility of threatened native forest ecosystems and the productivity of commercially important tree species to future climate change. First, findings related to the response of shade leaf physiology to dynamic light environments contributes to the overall understanding of canopy C gain in *Eucalyptus* trees. This utilization of sunflecks may play a critical role in productivity of *Eucalyptus* open-forests, specifically dry sclerophyll forests, in Australian ecosystems. Canopy cover in these open forest types likely allow for frequent sunflecks of high intensity at varying lengths. Additionally, many *Eucalyptus* species are characterized by steep leaf angles which can alter light penetrating the canopy, leaf physiology, radiation loads and C gain [@cowan1981coping; @king1997functional; @james2000leaf; @falster2003leaf]. Integration of these research findings with the functional role of leaf orientation may explain how *Eucalyptus* trees maintain positive C and energy balance in resource poor ecosystems and may be applicable to improve commercial stand productivity through thinning or pruning.

\
Second, aspects of leaf physiology and C allocation in these *Eucalyptus* trees species were less sensitivity to manipulations of warming, eC~a~ and drought than hypothesized. *Eucalyptus* trees are often characterized as being highly adaptable in order to cope with Australia’s prevailing climate and soils. It is possible that this adaptability plays a role in the observed stability of ecophysiological processes across the duration of these experiments (months to years). Consequently, warming treatments and simulated droughts may not have been of large enough magnitude to elicit functional plant response within experimental time frames. However, these results should by no means be used to conclude that Australian forest ecosystems are overly resilient to future climate regimes. Future climate scenarios predict increased frequency of extreme daily temperatures, heat waves, and limited water resources due to higher temperature and decreased rainfall in Australia [@ipcc2014]. Importantly, this research emphasizes that further empirical data quantifying C allocation to specific tissue, flux and ecosystem pools are critical in uncovering the drivers of tree responses to climate. Continued investigation of the cumulative impacts of eC~a~, warming and drought on *Eucalyptus* tree growth and fitness, such as the WTC experiments, will develop our ability to predict ‘tipping points’ for Australian forest ecosystems under future climate change.

# References {.unnumbered}
