---
title: ""
author: ""
date: ""
output:
  word_document:
    reference_docx: manuscriptstyle.docx
  pdf_document: default
  html_document:
    number_sections: yes
csl: tree-physiology.csl
bibliography: references.bib
---

```{r, results="asis", echo=FALSE, warning=FALSE}
library(knitr)
opts_knit$set(root.dir = '../')
```


# Abstract 

Plants must utilize external resources including light, CO~2~, water and mineral nutrients to fuel photosynthetic carbon (C) gain.  This photoassimiliate is then allocated within the plant as the essential C resource for growth, maintenance and storage. Theory and observation suggest that C allocation and leaf physiology are optimized to maintain functional balance for external resource capture and to maximize C gain. However, the impacts of a changing climate may disrupt the proposed balance of C allocation between above and belowground pools. Variation in resource distribution and leaf physiology within tree canopies is also not fully understood, thus all canopy leaves may not follow theories of leaf optimal behaviour. These unanswered questions regarding C uptake and fate of assimilated C inhibit our ability to precisely test the coordination between canopy A and growth. Therefore, this PhD research was designed to investigate how strongly resource allocation in Eucalyptus species, including external plant resources and photosynthetic C assimilate, are correlated to whole tree biomass growth. My goal was to measure aspects of resource allocation and C uptake across different scales, from leaf to whole tree, to generate a greater physiological understanding of the processes which define tree growth and the sensitivity of these processes to changing environments.

\
First, I determined whether manipulations of soil volume would limit growth in *Eucalyptus tereticornis* seedlings by disrupting the balance between source and sink activity. Seedlings were grown in a large range of container sizes and planted containers flush to the soil alongside naturally planted seedlings.  Aboveground growth of seedlings in containers was negatively affected soon after the experiment started. Despite large reductions in growth across soil volume treatments, dry mass partitioning to leaves, stems and roots was similar for all seedlings after 120 days. Leaf photosynthetic capacity decreased in containers compared to free seedlings, and was correlated to both leaf nitrogen (N) content and starch accumulation. Although belowground sink limitation resulted in down regulation of A, a mass balance seedling growth model concluded that these reductions were not large enough to explain observed growth responses. As A and growth were not tightly coordinated, excess photosynthetic C not attributed to biomass resulted in seedlings with soil volume restriction. Quantifying the fate of this excess C will be essential in evaluating feedbacks between sink strength and leaf C uptake in future studies.

\
Second, I investigated how light gradients within *Eucalyptus tereticornis* tree canopies affect the distribution of plant resources that define photosynthetic capacity of sun and shade leaves.  Additionally, I measured the capacity of shade leaves to adjust their physiological behaviour and increase C uptake when sunflecks occur. Trees were grown in climate controlled  whole tree chambers under prevailing ambient and warmed (+3 °C) treatments and leaf gas exchange was coupled with online carbon isotope discrimination to measure A, stomatal conductance (g~s~) and mesophyll conductance (g~m~) of sun and shade leaves.  Photosynthesis rates were reduced by ca. 40 % in shade leaves associated with a 75 % reduction in photosynthetically active radiation compared to sun leaves.  Photosynthetic capacity (ca. 20 % lower Vcmax and Jmax) and leaf N were also lower in shade leaves than sun leaves however, similar rates of g~s~ were observed between leaf types. Leaf C~i~, estimated from both leaf $\delta$^13^C and gas exchange, was higher in shade leaves than sun leaves. Here, the optimization theory hypothesis that C~i~ should be optimized throughout the canopy was rejected because shade leaves used more water with lower rates of A, as compared to sun leaves. When light intensity was increased from low light to high light for shade leaves both g~s~ and g~m~ increased rapidly, leading to increases in A greater than sun leaves at the same high light environment. This rapid response of g~m~ with light enables shade leaves to respond quickly to sunflecks and represents a new mechanism underpinning leaf gas exchange responses to light. These findings reveal that plant resources within a canopy may be distributed to utilize sunflecks and the dynamic physiological responses of shade leaves to altered light environments must be accounted for when upscaling leaf level measurements to predict whole canopy C gain. 

\
Finally, I examined how whole tree C flux correlated to tree biomass growth and whether elevated [CO~2~] and drought treatments altered C allocation patterns above or belowground in *Eucalyptus saligna* trees. Trees were grown in climate-controlled whole tree chambers (WTCs) over a period of two years with interacting treatments of two [CO~2~] (380 ppm and 620 ppm) and two watering regimes (well-watered and a four month drought). Additionally, we utilized a novel approach to calculated total belowground C allocation (TBCA) for each WTC as the residual between the aboveground net CO~2~ flux and aboveground C mass. Measured cumulative aboveground net CO~2~ flux correlated positively to whole tree C mass production and leaf area over the final eleven months of the experiment. Contrary to previous studies, biomass partitioning to roots and cumulative TBCA were unaffected by either elevated CO~2~ or drought treatments. As a fraction of total aboveground net C flux, TBCA was found to remain relatively stable across daily time steps for all trees. Increases in C allocation to leaves were detected in elevated CO~2~ treatments, while the effects of a 4 month drought were negligible on C allocation in aboveground tissues.  These results reveal how climate change factors impact the investment of photosynthetic C in a *Eucalyptus* tree species and provide evidence that belowground processes may not be as sensitive to global change factors as previously thought. 

\
In conclusion, this PhD research addressed questions regarding resource allocation in Eucalyptus tree species by linking leaf physiology to whole canopy C gain and allocation of photosynthetic C to whole tree growth. This study confirms that the availability and distribution of resources required for A define canopy C uptake, yet within canopy leaf physiology does not follow prevailing optimal theory. Results from this work then reveal how quantifying the fate of photosynthetic C among tissue and ecosystem pools, beyond biomass production, is imperative to accurately assess the impacts of environmental change on tree productivity. This research offers critical empirical data needed to refine process based models which predict canopy C gain from rates of A and forest growth models where C allocation is represented.  Ultimately, this work contributes valuable information regarding the physiological and growth responses of iconic *Eucalyptus* tree species essential for reconciling the impacts of resource availability and global climate change on fragile Australian ecosystems and the productivity of *Eucalyptus* plantation forests. 

# Chapter 1 General Introduction

### Overview

*Resource allocation in plants*

\
Plants need to extract resources including light, CO~2~, water and mineral nutrients to support growth, reproduction and fitness. To accomplish this each plant must concentrate resources from dilute surroundings, which requires energy, appropriate tissues for uptake and a transport system to deliver resources to their required destination [@grace1997allocation]. The uptake of nutrients from roots is necessary for leaf growth and leaves then fix the C, via A, required for growth of the entire plant. This assimilated C from source leaves, in the form of simple sugars, then becomes the essential C resource that must be allocated to the growth and maintenance of tissues or as a storage pool of carbohydrates. As a result, growth is driven by several simultaneous processes, including A, C investment among organs, resource acquisition and metabolic costs [@korner2006plant; @fourcaud2008plant].

\
*Resource allocation theory*

\
Theoretically, growth will be maximized when investment into the acquisition of any single resource from the environment leads to an equivalent increase in growth [@bloom1985resource]. The two critical assumptions of allocation theory are that the resource in question is in fixed supply and that allocation among competing functions is mutually exclusive [@bazzaz2000reproductive]. Thus, trade-offs between different tissue C sinks will exist as resources are invested within the plant. Allocation of newly acquired resources to different tissues will then affect subsequent rates of capture of CO~2~ and soil resources [@shipley2002balanced]. In resource saturated environment plants should maximize growth by allocating resources to leaves to increase C acquisition [@monsi2005factor]. Resource availability, however, is rarely saturated in natural ecosystems. As a result, differential allocation of external resources and assimilated C to different tissue or ecosystem components is commonly observed in plant species.

\
Differential resource allocation patterns within plants have led to two main theories regarding allocation strategies.  First, the balanced growth hypothesis suggests that individual plant tissues should provide a ‘balanced internal economy’ as each component supplies resources for the other [@davidson1969effect]. This functional equilibrium between tissues can then be adaptive if conditions limit A or soil nutrient uptake [@cannell1985attributes]. A balanced growth strategy infers that plants should allocate resources to the organ that is capturing the resource most limiting growth [@shipley2002balanced]. Alternatively, differential resource allocation in plant tissue is theorized to be a function of allometric trajectories of plant development related to plant size, independent of changes in nutrient supply [@muller2000effect]. In this strategy, investment into leaf mass increases with both stems and root, but not proportionally, as a greater allocation of biomass to the stem exists as a simple function of plant size [@zens2002sizing]. Consequently, plants are more likely to adjust tissue morphology, chemistry, metabolism or turnover to alter resource capture, instead of adjusting allocation to biomass components [@reich2002root]. 

\
*Allocation of external resources in trees*

\
Incident PPFD declines exponentially with cumulative leaf area index, creating steep light gradients within tree canopies [@monsi2005factor] and changing irradiance strongly affects rates of A [@evans1995carbon]. As costs and limitations of light harvesting prevent plants from exposing all leaves to full sun [@niinemets2010review], it follows that a substantial portion of canopy C assimilation should occur in leaves with the highest exposure to light. Consequently, the distributions of resources required for A are partially defined by canopy light gradients. As the photosynthetic capacity of leaves is related to its N content [@field1986photosynthesis], a larger investment in N to the upper canopy should yield a larger return from whole canopy C assimilation [@ellsworth1993canopy]. The supply of water also imposes limits photosynthetic C gain through direct limitations on leaf level physiology. The stomatal resistance to CO~2~ uptake is a function of the balance between transpiration losses and leaf water potentials [@farquhar1982stomatal] and sun leaves frequently experience greater water limitations in the upper canopy [sellin2008effects; niinemets2012optimization]. Thus, photosynthetic N investment in the upper canopy will be ineffective in enhancing A if water supply is insufficient [@niinemets2012optimization; @peltoniemi2012co]. Overall, the allocation of soil resources within the canopy constrains leaf physiology and photosynthetic capacity, thereby regulating the efficiency of light and CO~2~ uptake.    

\
*Fate of assimilated carbon*

\
Carbon allocation represents the fraction of net primary productivity distributed to different tissue and ecosystem components above and belowground.  In trees, C allocation encompasses investment into tissue biomass production as well as fluxes including respiration, exudation and turnover rates [@litton2007carbon]. A shift in C allocation to any of these components likely represents an adaptive response of trees when environmental conditions change. The fate of this assimilated C is also regulated by the delicate balance between source leaf activity and the C sink strength of the different biomass pools. For example, the sensitivity of C source and sink activities to water and nutrient controls could lead to an imbalance between C supply and C used for tissue growth and respiration [@fatichi2014moving]. Additionally, imbalances between source and sink activity can led to investment into carbohydrates synthesis as a transient C storage sink [@paul2001sink]. This makes separating of the investment of C between biomass production and other flux components vital when assessing temporal and spatial patterns of tree growth.

\
As woody plants have highly integrated systems of competing carbohydrate sinks, growth should principally depend on the allocation of leaf C assimilate among different sink organs [@kozlowski1992carbohydrate; @lacointe2000carbon]. Due to the law of conservation of mass, it is theoretically possible to track the fates of this assimilate from leaf C uptake to their eventual destination in above and belowground pools. Gaining an understanding of the sensitivity of these processes to environmental change is crucial for predicting future terrestrial C cycling [@friedlingstein1999toward], as there is currently little consensus on how C allocation should be modelled [@franklin2012modeling; @de2014does]. Mass balance principles also allow the coordination between canopy C assimilation and whole tree growth to be investigated over varying temporal scales. Success of this approach, however, depends on the ability to account for within canopy variation when estimating net canopy C gain [@de1997simple; @linderson2012up] or to empirically measure whole tree flux [@medhurst2006whole; @barton2010whole]. Although mass balance approaches can be used to quantitatively asses tree C allocation, few studies so far have been able to provide direct empirical measurements of C allocation among component pools [@klein2015].

\
*Eucalpytus tree species as model for research*

\
Research on *Eucalyptus* trees is ecologically important for Australia as it is the most dominant tree genus [@boland2006forest]. *Eucalyptus* forests are the continent’s most common forest type, covering about three-quarters of Australia’s native forests (92 million hectares) and occurring in all but the continent’s driest regions [@ASOFR2013]. *Eucalyptus* tree species are also economically important globally as they are commonly cultivated in plantations due to fast growth.  Despite the fact that only a few *Eucalyptus* species have natural ranges outside continental Australia [@pryor1981eucalyptus], *Eucalyptus* trees are grown in plantations in over 90 countries [@booth2013eucalypt]. This is because *Eucalyptus* species have been shown to exhibit both adaptive plasticity and genetic specialisation to spatial variation in climate [@byrne2013adaptation]. Currently, the global plantation area of Eucalypts totals nearly 20 million hectares, accounting for around 15 % of the world’s total plantation forests [@IUFRO2015]. Consequently, this iconic Australian tree species is an excellent model to investigate strategies of resource allocation in trees facing global climate change.

### Current Knowledge Gaps

\
*Resource allocation in trees*

\
The distribution of assimilated C is a primary determinant of plant growth [@friedlingstein1999toward], yet our knowledge of the mechanisms by which allocation is regulated is poor [@poorter2012biomass].  A key issue with drawing generalized conclusions about the plasticity of C allocation in trees is with the inconsistency in terminology used to define C allocation to specific tissue or ecosystem components [@litton2007carbon.]. Biomass partitioning should not be confused with the allocation of newly fixed photosynthates to different organ systems, as the measured biomass at any time point represent the cumulative result of dynamic C allocation over time [@poorter2015does]. This dynamic C allocation includes losses through respiration, exudation and turnover as well as transient C storage pools. As C allocation integrates all of these processes, it is extremely difficult using current methods to assess C allocation in whole trees. Disentangling the effects of resource supply on shifts in C allocation is often assessed in plants across “snapshots” in time, which should be done with caution [@reich2002root]. This is because of plants have developmental shifts in biomass partitioning, independent of resource supply, as they age [@muller2000effect; @poorter2015does].  Additionally, supplies of light and soil resources fluctuate continuously, making equilibrium with allocation at any “snapshot” highly unlikely [@shipley2002balanced].

\
The allocation of photosynthetic C above and belowground is an important factor in terrestrial C cycling, yet our understanding of how global change impacts C allocation is incomplete [@litton2007carbon; @warren2012timing]. As accurately measuring tree C allocation remains a difficult task, especially belowground, drawing conclusions which are applicable to whole plants or ecosystems remains a challenge. Currently, the representation of C allocation lags behind A in applied forest models [@friedlingstein1999toward; @franklin2012modeling; @iversen2014terrestrial]. This inefficiency in representing C allocation accurately in trees is of major concern due to the potential for forest ecosystems to sequester C in a changing climate. This deficiency requires more empirical data measuring patterns of tree C allocation under multi-factor global change manipulations. This is because understanding forest responses to global change will dependse on disentangling complex relationships between interacting factors [@rustad2008response]. However, this will require novel experiments and approaches to better quantify shifts in C allocation above and belowground in future studies. 

\
*Coupling of photosynthesis and tree growth*

\
At long enough time scales A and respiratory losses together determine net canopy C balance and will be coordinated to plant growth. At shorter temporal scales, however, growth can instead be mediated by tissue C storage pools. This had led to the long standing debate over how strongly plant growth is controlled by either source or sink activity [@sweet1966role; @korner2013growth]. Studies manipulating either source activity (CO~2~ fumigation or defoliation) or sink activity (fruit removal, girdling or low growth temperatures) have not reached consensus when addressing this debate.  This uncertainty arises from the difficulty in measuring the balance between C uptake and the fate of assimilated C among pools with long (biomass) or short (carbohydrate storage, respiration, exudation) retentions times. When shifts in carbohydrate storage, tissue respiration or turnover rates occur rates of C assimilation may not necessarily reflect biomass production at a given time point [@rocha2006linking; @litton2007carbon; @gough2008multi]. To assess this balance will likely require integration of empirical and modelling approaches to assess leaf physiological and whole plant responses to manipulations of source-sink activity. To address this debate, new approaches are needed to test how interactions between source and sink activity affect the fate of assimilate C across different temporal scales. 

\
*Within canopy resource utilization*

\
As A has a saturating response with light, and N is highly correlated with photosynthetic capacity, it is commonly assumed that N should be distributed proportional to light availability within tree canopies. However, observed distribution of N within canopies is often shallower than optimal theory suggests [@peltoniemi2012co]. Additionally, the inability to distribute water from the soil to the upper canopy may negatively impact the distribution of photosynthetic N to canopy light availability [@niinemets2012optimization, @peltoniemi2012co]. Whether insufficient hydraulic supply results in the observed suboptimal canopy N gradients has yet to be empirically tested. Assessing leaf C gain as a function of light availability is also made difficult by frequent light fluctuations within a canopy, via sunflecks.  How leaves respond to sunflecks is often studied in deep shade conditions in the understory, thus limiting our knowledge of how resource allocation and leaf physiological behaviour may be preferentially adjusted to maximise responses to sunflecks with tree canopies.

\
Additionally, leaves have been proposed to exhibit optimal physiological behaviour in order to maximize C gain while minimizing associated costs [@thornley1972model].  In trees, leaf physiology often focuses on full sun leaves and relationships between leaf physiological behaviour and the availability of N, water and light between sun and shade leaves requires further attention. For example, g~s~ has been hypothesized to be distributed within a canopy to utilize supplies of light, N and water to maximize A [@peltoniemi2012co]. To date, however, no clear picture has emerged on the relationship between g~s~ and A within canopies [see @jifon2003moderate; @tissue2006spatial; @sellin2010variation]. As g~m~ also limits A, complex relationships may exist between canopy light gradients, leaf N and g~m~. Unfortunately, a scarcity of values for g~m~ within tree canopies [see @lloyd1992low; @warren2003transfer; @piel2002effect; @warren2007internal] hinders our ability to relate individual leaf physiological behaviour to optimal canopy C uptake. As the CO~2~ drawdown from the atmosphere to the site of carboxylation includes g~s~ and g~m~, relationships between A with light availability, N and water within canopies will require the integration of both physiological parameters in future experiments.

### Thesis Objectives
The overall research goal is to evaluate how trees adjust their growth and physiology to optimize resource uptake and C gain. Specifically, this PhD research addresses knowledge gaps of how tissue C allocation, source and sink regulation and resource distribution affect the coordination between A and whole tree growth. In order to investigate key mechanisms that drive patterns in resource allocation in trees this research was carried out across multiples scales, from leaf isotope discrimination across the photosynthetic CO~2~ flux pathway to tissue specific biomass partitioning to total belowground C allocation. Understanding how resource allocation is correlated with individual leaf physiological behaviour within tree canopies is crucial in accurately determining the capacity for whole canopy C assimilation, which is the essential resource for tree growth.  Aspects of this research use manipulations of key global change factors, including elevated CO~2~, warming and drought to investigate the plasticity of observed physiological and growth responses to future climate scenarios. An improved understanding of how C is allocated within trees will supply much needed empirical data for applied forest models where C allocation is currently poorly represented. 

\
This research focuses on two Australian tree species, *Eucalyptus tereticornis* and *Eucalyptus saligna*, which have important roles in both native forests ecosystems and as commercial plantation timber. *Eucalyptus tereticornis* is part of the critically endangered Cumberland Plain ecological community in the Sydney Basin bioregion at the threat of extinction and *Eucalyptus saligna* is part of the critically endangered Blue Gum High Forest ecological community in the Sydney Basin Bioregion with a highly restricted geographic distribution [@hughes2011web]. Both of these species are part of the “big nine” *Eucalyptus* species group which accounts for more than 90 % of planted *Eucalyptus* forests worldwide [@stanturf2013eucalyptus]. As a result, the core findings of this PhD research have both conservation and commercial applications in addressing the productivity of these two important tree species in the face of global climate change. For example, considerable uncertainty remains as to the magnitude of CO~2~ fertilization on this continent as much of the vegetation is already under nutrient and/or water limitation [@hughes2003climate]. 

\
This research was conducted using the state of the art Whole Tree Chamber experiment as well as a novel field-based seedlings container study at Western Sydney University. Using the aforementioned *Eucalyptus* tree species, theories of optimal physiological behaviour and resource allocation through functional balance were tested at several growth stages. Leaf based data were combined with tissue biomass production and canopy C fluxes to develop a better understanding of how resources are allocated to optimize whole tree growth. Empirical data were also integrated with a seedling growth model to test how resource limitation impacts the coordination between A and growth. Specifically, this thesis aimed to address current knowledge gaps by answering the following main questions:

\
1.	**Where does the carbon go?** 
\
How will biomass partitioning and carbon allocation in *Eucalyptus* trees be affected by global change and belowground resource limitation?

\
2.**When do photosynthesis and growth not add up?**
\
What do mass balance approaches reveal about the coordination of growth and photosynthesis at different temporal scales?

\
3.	**Are whole canopies optimized for carbon gain?**
\
How does resource availability within *Eucalyptus* tree canopies interact with dynamic physiology of sun and shade leaves to maximize canopy carbon gain?

### Thesis Outline

**Chapter 2** was designed to address thesis questions 1 & 2 by manipulating belowground sink strength in *Eucalyptus tereticornis* seedlings, via different container sizes, in a novel field-based experimental design. The effects of belowground resource limitation were then used to investigate patterns in biomass partitioning between container treatments and field grown seedlings. Empirically measured gas exchange parameters were then used to model daily C gain for each seedling to test the coordination between the down regulation of A and biomass production of seedlings with soil volume restriction. The sensitivity of this model to different C allocation scenarios was used to speculate possible fates of photosynthetic C not accounted for in the default model. Results of this study are then used to address the ongoing debate over source or sink controls of A and growth. The flexibility of this mass balance modelling approach is used to highlight the importance of quantifying C allocation when evaluating the impacts of resource limitation on tree seedling growth.

\
**Chapter 3** addressed thesis question 3 by combining leaf gas exchange with online C isotope discrimination to measure the responses of sun and shade leaf physiology to light availability. The distribution of leaf N and leaf hydraulic conductance within *Eucalyptus tereticornis* canopies where examined to test if the resources required for A were preferentially invested into sun leaves, according to optimal theory, to maximize whole canopy C gain. The physiological capacity of shade leaves to respond to increases in light availability was quantified to determine if shade leaves “lie in wait” for sunflecks. Trees were grown in climate controlled WTCs under ambient and elevated air (+3&deg;C) temperature treatments to test the impacts of future climate warming on each of these processes. Rarely have relationships between A and both stomatal conductance and mesophyll conductance been quantified within tree canopies, thus results from this experiment are used to reveal potential new mechanisms underpinning leaf gas exchange responses to light. Combined results from canopy resource allocation and leaf physiology yield valuable information regarding the caution that needs to be taken when upscaling leaf level measurements to the canopy. Empirical data from this experiment improve our ability to predict whole canopy C gain by prioritizing both sun and shade leaf physiology, which may be optimized differently.

\
**Chapter 4** addresses thesis questions 1 & 2 by quantifying high resolution net canopy photosynthesis measurements and C allocation in *Eucalyptus saligna* trees grown under interacting drought and elevated CO~2~ treatments. The unique WTC experimental design was used to measure cumulative net aboveground C fluxes which were compared to canopy leaf area and biomass production. How interacting climate change factors impacted C allocation to various above and belowground pools was then evaluated across various temporal scales. Results from this experiment help emphasize the need to correctly define individual aspects of tree C allocation and highlight the importance of separating impacts on measured biomass from flux based components of C allocation when evaluating tree growth responses to climate change. As empirical measurements of C allocation are difficult to obtain, especially with belowground processes, these results provide much needed empirical data to validate processes based model where C allocation is represented. This includes applying a novel framework, provided by the WTCs, to calculate a more reliable estimate of the sensitivity of TBCA to global climate change. 

\
**Chapter 5** presents the synthesis of the major findings in my PhD research as they relate to each main thesis question. First, biomass partitioning remained relatively conserved across manipulative experiments with *Eucalyptus* seedlings and trees, however mass balance approaches confirm that shifts in C allocation likely occurred as these two *Eucalyptus* species were impacted by changing environments. Combined results from Chapters 2 & 4 are used to discuss how observed responses of biomass partitioning and C allocation correspond to prevailing theory and how these mass balance approaches have improved our understanding of the investment of photosynthetic C in trees. Second, I show that coupling between total C carbon gain and tree growth can be disrupted over shorter experimental time frames, while over longer time scales they are strongly correlated as a function of leaf area. Results from Chapter 2 use empirical data and modelling approaches to address the current debate over source and sink control over seedling growth, while Chapter 4 is used to discussed how unique measurements of net canopy photosynthesis correlate to tree productivity under future climate scenarios. Last, I show that sun and shade leaves exhibit different physiological behaviour in order to utilize differential availability of external resources within *Eucalyptus tereticornis* canopies. Results from Chapter 3 are used to show that shade leaf physiology is likely optimized differently from sun leaves in order to respond to sunflecks, which has important consequence for current theories regarding how resources are allocated to optimize canopy C gain.


# References {.unnumbered}
