---
title: ""
author: ""
date: ""
output:
  word_document:
    reference_docx: manuscriptstyle.docx
  pdf_document: default
  html_document:
    number_sections: yes
csl: tree-physiology.csl
bibliography: references.bib
---

```{r, results="asis", echo=FALSE, warning=FALSE}
library(knitr)
opts_knit$set(root.dir = '../')
```

# Acknowledgements

“I am the Lorax. I speak for the trees. I speak for the trees for the trees have no tongues.”
--Dr. Seuss

\
I dedicate this thesis to my mother, for she has been my inspiration to become a scientist for as long as I can remember. Her passion for the natural world is infectious and her ability to pass her scientific knowledge to others is inspirational. It is because of you that I flip over rocks to see what is hiding underneath.

\
I would equally like to acknowledge my father for instilling in me the work ethic and drive that has carried me to this point. Without his undying support I might never have achieved the level of success I have been afforded. You share in all my triumphs and my failures as a

\
To Caroline, none of this would be possible without you by my side. You have been a rock when I need a foundation and a light when my path seems lost. Je t'aime.

# Statement of Authentication
The work presented in this thesis is, to the best of my knowledge and belief, original
except as acknowledged in the text. I hereby declare that I have not submitted this
material, either in full or in part, for a degree at this or any other institution.

## Table of Contents

## LIST OF TABLES

**Table 2.1**.Responses of plant and leaf characteristics of *Eucalyptus tereticornis* seedlings to soil volume treatments. Each value reflects the mean(standard error) for each treatment. Seedling mass and leaf $\delta$^13^C values are from final harvest. Values of leaf starch, sugars, nitrogen and SLA represent overall means across measurement campaigns (n=6). Different letters represent significant differences between treatments. The volume effect P value represents the overall difference between seedlings with soil volume restriction and the control seedlings.

\
**Table 2.2** Responses of root characteristics of *Eucalyptus tereticornis* seedlings to soil volume treatments. Each value reflects the mean(standard error) for each treatment. All values are from the final harvest. Values for FRLD are only calculated for seedlings in containers as free seedlings have potentially unlimited soil volume to exploit. Different letters represent significant differences between treatments. The volume effect P value represents the overall difference between seedlings with soil volume restriction and the control seedlings, except for FRLD which represents only differences between seedlings in containers.

\
**Table 2.3** Responses of leaf level gas exchange parameters of *Eucalyptus tereticornis* seedlings to soil volume treatments. Each value reflects the mean(standard error) for each treatment. A~max~, R and g~s~ are each measured at 25 &deg;C. Values of A~max~, g~s~ and g~1~ represent overall means across measurement campaigns (n=6). R, J~max~ and Vc~max~ values are means of two measurement campaigns at beginning and end of gas exchange measurements. Different letters represent significant differences between treatments. The volume effect P value represents the overall difference between seedlings with soil volume restriction and the control seedlings.

\
**Table 2.S1**. Seedling growth model default parameters.

\
**Table 3.1**. *Eucalyptus tereticornis* leaf morphological and physiological traits between full sun and shade leaves under ambient and elevated temperature treatments. Leaf mass per area, N~a~, $\delta$^13^C, $\Psi$~pd~, $\Psi$~l~ and K~l~ values represent treatment mean (&pm; 1 standard error) across measurement campaigns (n=6). Values of Vc~max~ and J~max~ are treatment mean (&pm; 1 standard error) from AC~i~ curves measured in each chamber at saturating light. Units of LMA and Leaf N~area~ are g m^2^, K~l~ is mmol m^-2^ s^-1^ MPa, WP is MPA and $\delta$^13^C is &permil;. Different letters represent significant differences between leaf type and temperature treatments. The P value represents the overall effect between each unique combination of leaf type and temperature treatment for each trait.

\
**Table 3.2**. Responses of *Eucalyptus tereticornis* leaf gas exchange parameters for sun and shade leaves under ambient and elevated temperature treatments. Each value reflects the mean (&pm; 1 standard error) for each treatment across gas exchange campaigns (n=6). Units for A and E are $\mu$mol m^-2^ s^-1^, for g~s~ and g~m~ are mol m^-2^ s^-1^ and for VPD are kPa. Different letters represent significant differences between leaf type, light environment and temperature treatments. The P value represents the overall effect between each unique combination of leaf type, light environment and temperature treatment for each parameter.

\
**Table 4.1**. Final harvest C mass of above and belowground tissues, cumulative aboveground tree C uptake ($\text{F}_{c,T}$) and specific leaf area (SLA). Each value represents the mean (&pm; 1 standard error) for each treatment combination. Units for C mass and $\text{F}_{c,T}$ are g C, while SLA are cm^2^ g^-1^. For each variable, different letters represent significant differences between treatments from the overall model which includes C~a~ * drought interactions. P values represent overall differences of C~a~ or drought main effects and the C~a~ * drought interaction.

## LIST OF FIGURES

**Figure 2.1**. Soil volume treatment means &pm; standard error of height growth (a), diameter growth (b), and interpolated seedling leaf area (c) measured weekly of *Eucalyptus tereticornis* seedlings across the experiment duration in 2013.

\
**Figure 2.2**. Daily maximum and minimum temperature (a), total daily PPFD (b), and daily maximum vapour pressure deficit (c) across the experiment duration in 2013.

\
**Figure 2.3**. Soil volume treatment means of biomass partitioning to leaves, stems, and roots at harvest (a), bi-variate relationships between mass allocation to leaves and stems + roots (b) and leaf mass as a function of fine root biomass with &pm; standard error (c). For (b) lines represent standardized major axis fitting of the log-transformed allometric relationships of leaf mass fraction by treatment. For (c) the dashed line is the 1:1 relationship and the solid line represents the significant log-log model fit (R^2^ = 0.82) with equation: log(x) = 0.983(log(y)) - 0.036.

\
**Figure 2.4**. Soil volume treatment means &pm; standard error, across all measurement campaigns (n = 6), of light saturated rates of photosynthesis at 25&deg;C. Different letters represent significant differences between treatments.

\
**Figure 2.5**. Photosynthetic capacity, on a leaf mass basis, as a function of accumulation of leaf starch (a) and leaf nitrogen content without TNC (b).  Colors represent bins levels (n = 5) of both leaf starch and nitrogen grouped from low to high.  Lines represents predictions, for each bin level, from the linear mixed effects model equation of A~mass~ as a function of starch and nitrogen. The marginal R^2^ (fixed effects only) was 0.37 and the conditional R^2^ (fixed and random effects) was 0.48 for the complete model.

\
**Figure 2.6**. Total carbon mass for harvested and modeled seedlings versus predicted total carbon gain after 120 days (a) and  reductions in final seedling carbon mass, both modeled and observed, as a function of the reduction in leaf photosynthesis across treatments (b). For (a) the dashed 1:1 identifies the difference between net total leaf carbon gain and gross seedling production. For (b) both seedling carbon mass and daily carbon assimilation were first scaled to the free seedling control.

\
**Figure 2.S1**. Sensitivity testing of seedling growth model to different carbon allocation strategies including; constraints of leaf mass fraction to treatment specific final harvest values (a) and increases in respiration of non-leaf tissue components by 50 % (b).  Open and filled symbols represent default model and harvest values, while shaded symbols represent model sensitivity to each scenario by soil volume treatment. Both seedling carbon mass and daily carbon assimilation were first scaled to the free seedling control.

\
**Figure 3.1**. Bars represent the local light environment for sun and shade leaves during six gas exchange campaigns from October 2013 to April 2014. Means &pm; 1 standard error represent integrated PPFD, measured with a ceptometer, at the canopy height of each selected leaf. Each date represents the starting date for each measurement campaign. Points represent the mean (&pm; 1 standard error) daily maximum air temperature during each campaign period.

\
**Figure 3.2**. (a) ACi curves for sun and shade leaves at elevated (ET) and ambient (AT) temperature treatments. ACi curves were measured once on all trees, in February 2014, at 25°C and at saturating light (1800 $\mu$mols m^-1^ s^-1^). (b) The relationship between Vc~max~ and mean leaf N~a~ for each chamber, including sun leaves and shade leaves at low light. (c) The relationship between A and leaf N~a~ for sun and shade leaves measured under their ambient light and temperature conditions. For (b,c) the dashed line represents the significant linear model fit for all leaves, with a marginal and conditional R^2^ of 0.28 and 0.35 for (b) and 0.24 and 0.33 for (c).

\
**Figure 3.3**. The response of A to g~s~ (a) and g~m~ (b) for sun leaves measured at high light and shade leaves measured at both low and high light under their respective elevated and ambient temperature treatments. Lines represent either smoothed regressions from a generalized additive model fit (a) or linear model fits (b). Grey areas are 95% confidence intervals from the mean.

\
**Figure 3.4**. The mean &pm; 1 standard error of g~s~ (a), g~m~ (b) and A (c) of sun leaves and shade leaves at both low and high light pooled across six measurement dates.

\
**Figure 3.5**. (a) Response of instantaneous transpiration efficiency (ITE) to VPD for sun leaves and shade leaves at both low and high light with elevated and ambient temperature treatments. (b) The relationship between leaf $\delta$^13^C and leaf N~a~ for sun leaves at high light and shade leaves at low light. For (a) VPD is the leaf to air pressure difference inside the gas exchange cuvette and lines represent predictions from the optimal ITE model with a g~1~ value for each leaf type and treatment. For (b) the dashed line represents the significant linear model fit for all leaves with a marginal and conditional R^2^ of 0.41 and 0.45, respectively.

\
**Figure 3.6**. Relationship between the observed discrimination of ^13^CO~2~ measured during photosynthesis and measured C~i~/C~a~ for sun leaves measured at high light and shade leaves measured at both low and high light. The solid line represents the theoretical line for C3 plants from Evans et al. [-@evans1986carbon].

\
**Figure 3.7**. The mean &pm; 1 standard error of intercellular CO~2~ concentration (a), CO~2~ concentration in the chloroplasts (b) and CO~2~ drawdown from substomatal cavities to sites of carboxylation of sun leaves and shade leaves at both low and high light.

\
**Figure 3.S1**. Daily maximum and minimum temperature (a) and total daily PPFD (b) for each chamber across the experiment duration.

\
**Figure 3.S2**. Photosynthetic CO~2~ response (AC~c~) curves for sun and shade leaves at elevated and ambient temperature treatments. C~c~ values were predicted with g~m~, thus curves represent chloroplastic photosynthetic parameters at 25°C and saturating light (1800 $\mu$mols m^-1^ s^-1^). 

\
**Figure 3.S3**. Response of A (a), g~m~ (b) and C~i~-C~c~ to leaf temperature for sun leaves and shade leaves at low and high light. Shaded symbols represents each monthly measurement campaign. Solid lines, colored by leaf and light type, are fitted line for the relationship with each parameter and leaf temperature across all measurement campaigns. All parameters with no relationship are fitted with zero slope and the overall mean value for each treatment combination. Weak negative relationships with g~m~ and increasing leaf temperature were detected with sun and shade leaves under their local light environment (R^2^ = 0.16 and 0.08, respectively). 

\
**Figure 3.S4**. Response of VPD (a), g~s~ (b) and C~a~-C~i~ to leaf temperature for sun leaves and shade leaves at low and high light. Shaded symbols represents each monthly measurement campaign. Solid lines, colored by leaf and light type, are fitted line for the relationship with each parameter and leaf temperature across all measurement campaigns. All parameters with no relationship are fitted with zero slope and the overall mean value for each treatment combination. Leaf VPD inside the gas exchange cuvette was positively correlated with increasing leaf temperature for sun leaves and shade leaves at low and high light (R^2^ = 0.73, 0.58 and 0.72, respectively).

**Figure 4.1**. Conceptual diagram depicting the major components of C flow among plant components including; uptake via photosynthesis, allocation to component tissues, tissue respiration and root exudation. Net aboveground C uptake ($\text{F}_{c}$), shown in the shaded box, represents the flux of C measured within each WTC. With the WTC experimental design, total belowground C allocation (TBCA) is measured as the residual between $\text{F}_{c,T}$ and total aboveground C mass. 

\
**Figure 4.2**. Whole tree C mass as a function of cumulative aboveground C flux for each WTC tree. Values of cumulative aboveground net C flux were measured over the final eleven months of the experiment. Whole tree C mass represents the sum of bole, branch, leaf and root C mass from allometric estimates over the same time period. The dotted line is the 1:1 relationship and the solid line represents the significant overall linear model fit from the equation y = 0.56x + 878.2 (R^2^ = 0.86).

\
**Figure 4.3**. Estimated canopy leaf area for each WTC tree over the final eleven months of the experiment (April 2008 to March 2009). Estimates are based on height growth, litterfall rates and two leaf area estimates following Barton et al. [-@barton2012effects]. Color and line type distinguish the treatment combination for each WTC.

\
**Figure 4.4**. Treatment means of cumulative aboveground C flux as a function of mean daily canopy leaf area over the final eleven months of the experiment. The solid line represents the significant overall linear model fit (R^2^ = 0.77) from the equation: y = 611.9x + 2791.2. Separate 95% confidence intervals are shown for linear regression between $\text{F}_{c,T}$ and mean leaf area for aC~a~ and eC~a~ treatments.

\
**Figure 4.5**. Treatment means of C mass fractions of leaves (a), stems (branches+boles) (c) and roots (e) as a function of tree size, via whole tree C mass. Treatment means of C allocation to leaves (b) and stems (d) as a function of cumulative aboveground net C flux. Root C allocation could not be estimated as root turnover was not known. Values for C mass fractions are calculated from final harvest biomass totals. Values for C allocation are estimated from cumulative total aboveground net C flux over the final eleven months of the experiment. Solid lines represent overall linear model fit for leaf, stem and root mass fractions (R^2^ = 0.53, 0.26 and 0.01, respectively), as well as leaf and stem C allocation (R^2^ = 0.39, 0.01, respectively).

\
**Figure 4.6**. Cumulative aboveground net C flux and additive C allocation to individual tree components from 15 April 2008 to 16 March 2009. Each panel represents mean values for each treatment combination (n=3). Both aboveground net C flux and tissue C allocation where set to 0 on 15 April 2008 in order to track the allocation of C in daily time steps. Root C mass, predicted from the logarithmic relationship between above and belowground mass partitioning of pre-planting seedlings and harvested trees, is shown on the last date.

\
**Figure 4.7**. Treatment means &pm; 1 standard error of cumulative aboveground net C flux, TBCA, and the residual belowground C flux ($\text{F}_{c,r}$). Values of cumulative aboveground net C flux were measured over the final eleven months of the experiment. Values for TBCA are the residual between the cumulative C flux and total C mass aboveground estimated from allometric surveys over the same time period. Values for $\text{F}_{c,r}$ were calculated as the residual between TBCA and root C mass predicted on the last date of the eleven month period. 

\
**Figure 4.8**. Total belowground C allocation as a function of cumulative aboveground net C flux across the final eleven months of the experiment. Carbon mass aboveground was estimated from allometric surveys, interpolated on a daily time scale and then subtracted from the aboveground net C flux to quantify TBCA. Individual lines represent treatment means, with color and line type distinguishing treatment combinations. The dotted line represents a theoretical investment of 50 % of aboveground net C flux towards TBCA.

\
**Figure 4.S1**.
Root mass as a function of shoot mass in *Eucalyptus saligna* for potted seedlings harvested before planting of WTC trees (n=17) and WTC trees harvested after 2 years (n=12). Potted seedlings were grown in 25 l pots inside each WTC, while chamber [CO~2~] treatments conditions were maintained. The solid line represents the significant log-log model fit (R^2^ = 0.98) from the equation: log(x) = 0.77(log(y)) + 0.43.

\
**Figure 4.S2**.
Cumulative aboveground net C flux and additive C allocation of individual tree components from 2008-4-15 and 2009-3-16. Panels represent each individual WTC. Both aboveground net C flux and tissue C allocation where set to 0 on 2008-4-15 in order to track the allocation of C in daily time steps. Total root C mass, predicted from the log relationship between above and belowground mass partitioning of pre-planting seedlings and harvested trees, is shown on the last date.


# LIST OF ABBREVIATIONS

*A~n~*  Net leaf photosynthesis rate
\
A~c~ Component specific biomass partitioning??
\
aC~a~ Ambeint CO~2~ treatment
\
AC~i~ Photosynthetic CO2 response curves 
\
A~sat Leaf net photosynthesis at saturating light
\
A~max Leaf net photosynthesis at saturating light and CO~2~ concentration
\
AT  Ambient air temperature treatment
\
C Carbon
\
[CO~2~] CO~2~ concentration
\
C~a~ Atmospheric CO~2~ concentration
\
$\text{C}_{ab}$ Aboveground standing crop C mass
\
C~day~ Predicted daily carbon assimilation
\
C~i~ Intercellular CO~2~ concentration (or parital pressure)
\
C~c~ Chloroplastic CO~2~ concentration (or parital pressure)
\
$\text{C}_{r,T}$  Total C mass of roots
\
E Leaf transpiration
\
eC~a~ Elevated CO~2~ treatment
\
ET  Elevated air temperature treatment
\
FACE Free-air C0~2~ enrichment experiments
\
$\text{F}_{c}$  Net aboveground carbon uptake
\
$\text{F}_{c,r}$  Residual belowground C flux
\
free  naturally planted
\
FRLD Fine root length density
\
g~s~  Stomatal conductance
\
g~m~  Mesophyll conductance
\
ITE Leaf level instantaneous transpiration efficiency
\
J~max Naximum rate of photosynthetic electron transport 
\
K~l~ Leaf-specific hydraulic conductance 
\
LA Leaf area
\
LMA Leaf mass per unit area
\
LMF Leaf mass fraction
\
N  Nitrogen
\
N~a~ Leaf nitrogen on an area basis
\
N~f~ TNC-free leaf nitrogen content
\
PPFD  Photosynthetic photon flux density
\
Q~10~ Rate of change in respiration due to 10 &deg;C increase in temperature
\
R Leaf dark respiration rates
\
RMF Root mass fraction
\
SLA Specific leaf area
\
SLA~f~  TNC-free Specific leaf area
\
SMF Stem mass fraction
\
TBCA Total belowground carbon allocation
\
TNC Total non-structural carbohydrate
\
TDL Tunable diode laser
\
Vc~max Maximum rate of Rubisco carboxylation 
\
VPD Vapour pressure deficit
\
VPDP standard Vienna Pee Dee Belemnite
\
WUE Water-use efficiency
\
WTC whole-tree chambers
\
$\delta$  isotope discrimination
\
$\Delta$ Carbon isotope discrimination during C3 photosynthesis 
\
$\Psi$~l~ Midday leaf water potential
\
$\Psi$~pd~  Predawn leaf water potential
\
$\sigma$~s~ Self shading parameter

# Abstract 

Plants must utilize external resources including light, CO~2~, water and mineral nutrients to support photosynthetic carbon (C) gain.  This photoassimilate is then allocated within the plant as the essential C resource for growth, maintenance and storage. Theory and observations suggest that C allocation and leaf physiology are optimized to maintain functional balance for external resource capture and to maximize C gain. However, the impacts of a changing climate may disrupt the proposed balance of C allocation between above and belowground pools. Variation in resource distribution and leaf physiology within tree canopies is also not fully understood, thus all canopy leaves may not follow theories of leaf optimal behavior. These unanswered questions regarding C uptake and fate of assimilated C inhibit our ability to precisely test the coordination between canopy photosynthesis and growth. To address these broad ecological questions, this PhD research utilized a diverse set of experiments which manipulated resource availability and climate factors on *Eucalyptus* tree species. My goal was to measure aspects of resource allocation and C uptake across different scales, from leaf to whole tree, to improve physiological understanding of the processes which define tree growth and the sensitivity of these processes to changing environments.

\
First, I determined whether manipulations of soil volume would limit growth in *Eucalyptus tereticornis* seedlings by disrupting the balance between source and sink activity. Seedlings were grown in a large range of container sizes and planted flush to the soil alongside naturally planted seedlings ('free').  Aboveground growth of seedlings in containers was negatively affected compared to free seedlings soon after the experiment started. Despite large reductions in growth across soil volume treatments, relative partitioning of mass to leaves, stems and roots was similar for all seedlings after 120 days. Leaf photosynthetic capacity decreased in containers compared to free seedlings, and was correlated to both leaf nitrogen (N) content and starch accumulation. Although belowground sink limitation resulted in a reduction of net leaf photosynthesis (*A~n~*), a mass balance model concluded that these reductions were not large enough to explain observed growth responses. As *A~n~* and growth were not tightly coordinated, the model predicted excess photosynthetic C not attributed to biomass in potted seedlings. Quantifying the fate of this excess C will be essential in evaluating feed-backs between sink strength and leaf C uptake in future studies.

\
Second, I investigated how light gradients within *Eucalyptus tereticornis* tree canopies affect the distribution of resources that define photosynthetic capacity of sun and shade leaves. Trees were grown in climate-controlled  whole tree chambers under prevailing ambient and warmed (+3 °C) treatments and leaf gas exchange was coupled with online C isotope discrimination to measure *A~n~*, stomatal conductance (g~s~) and mesophyll conductance (g~m~) of sun and shade leaves. Photosynthesis rates were reduced by ca. 40 % in shade leaves associated with a 75 % reduction in photosynthetically active radiation compared to sun leaves. Photosynthetic capacity (ca. 20 % lower Vcmax and Jmax) and leaf N were also lower in shade leaves than sun leaves however, g~s~ was similar. Leaf C~i~, estimated from both leaf $\delta$^13^C and gas exchange, was higher in shade leaves than sun leaves. Here, the optimization theory hypothesis that C~i~ should be optimized throughout the canopy was rejected because water use efficiency was lower in shade leaves, compared to sun leaves. When light intensity was increased from low light to high light for shade leaves both g~s~ and g~m~ increased rapidly, leading to increases in *A~n~* greater than sun leaves at the same high light environment. This rapid response of g~m~ with light enables shade leaves to respond quickly to sunflecks and represents a new mechanism underpinning leaf gas exchange responses to light. This capacity of shade leaves to adjust their physiological behavior and increase C uptake when sunflecks occur likely plays significant role in whole tree C uptake for some tree species. These findings reveal that plant resources within a canopy may be distributed to utilize sunflecks and the dynamic physiological responses of shade leaves to altered light environments must be accounted for when up-scaling leaf level measurements to predict whole canopy C gain. 

\
Finally, I examined how net aboveground C uptake correlated to tree biomass growth and whether elevated [CO~2~] and drought treatments altered C allocation patterns above or belowground in *Eucalyptus saligna* trees. Trees were grown in climate-controlled whole tree chambers (WTCs) over a period of two years with interacting treatments of two [CO~2~] (380 ppm and 620 ppm) and two watering regimes (well-watered and a four-month drought). Additionally, we utilized a novel approach to calculate total belowground C allocation (TBCA) for each WTC as the residual between the aboveground net CO~2~ uptake and aboveground C mass. Measured cumulative aboveground net C uptake correlated positively to whole tree C mass production and leaf area over the final eleven months of the experiment. Contrary to previous studies, cumulative TBCA was unaffected by either elevated CO~2~ or drought treatments. As a fraction of total aboveground net C uptake, TBCA was also found to remain relatively stable across daily time steps for all trees. Increases in C allocation to leaves were detected in elevated CO~2~ treatments, while the effects of a 4 month drought were negligible on C allocation in aboveground tissues.  These results reveal how climate change factors impact the investment of photosynthetic C in a *Eucalyptus* tree species and provide evidence that belowground processes may not be as sensitive to global change factors as previously thought. 

\
In conclusion, this PhD research addressed diverse questions regarding resource allocation in *Eucalyptus* tree species by linking leaf physiology to whole canopy C gain and allocation of photosynthetic C to whole tree growth. This study confirms that the distribution of photosynthetic resources constrain canopy C uptake, yet within canopy leaf physiology does not follow prevailing optimal theory. Results from this work reveal how quantifying the fate of photosynthetic C among tissue and ecosystem pools, beyond biomass production, is imperative to accurately assess the impacts of environmental change on tree productivity. This research offers critical empirical data needed to refine process based models which predict canopy C gain from rates of *A~n~* and forest growth models where C allocation is represented. Ultimately, this work contributes valuable information regarding the physiological and growth responses of iconic *Eucalyptus* tree species essential for reconciling the impacts of resource availability and global climate change on fragile Australian ecosystems and the productivity of *Eucalyptus* plantation forests. 

# Chapter 1 General Introduction

### Overview

*Resource allocation in plants*

\
Plants need to extract resources including light, CO~2~, water and mineral nutrients to support growth and reproduction. To accomplish this requires energy, appropriate tissues for uptake and a transport system to deliver resources to their required destination [@grace1997allocation]. The uptake of nutrients from roots is necessary for leaf growth. Leaves then fix the C, via net photosynthesis (*A~n~*), required for growth of the entire plant. This assimilated C from source leaves, in the form of simple sugars, is in itself an essential C resource that must be allocated to the growth and maintenance of tissues or is diverted to a storage pool of carbohydrates. As a result, growth is driven by several simultaneous processes, including *A~n~*, C investment among organs, resource acquisition and metabolic costs [@korner2006plant; @fourcaud2008plant]. Gaining an understanding of the sensitivity of these processes to environmental change is crucial for predicting future terrestrial C cycling [@friedlingstein1999toward], as there is currently little consensus on how C allocation should be modeled [@franklin2012modeling; @de2014does].

\
*Resource allocation theory*

\
Theoretically, growth under resouce limitation will be maximized when investment into the acquisition of any single resource from the environment leads to an equivalent increase in growth [@bloom1985resource]. The two critical assumptions of allocation theory are that the resource in question is in fixed supply and that allocation among competing functions is mutually exclusive [@bazzaz2000reproductive]. Thus, trade-offs between different tissue C sinks will exist as resources are invested within the plant. Allocation of newly acquired resources to different tissues will then affect subsequent rates of capture of CO~2~ and soil resources [@shipley2002balanced]. In resource saturated environments plants should maximize growth by allocating resources to support leaf growth to increase C acquisition [@monsi2005factor]. Resource availability, however, is rarely saturated in natural ecosystems. As a result, shifts in allocation of external resources and assimilated C to different tissue or ecosystem components can occur.

\
Shifts in resource allocation within plants have led to two main theories regarding allocation strategies. First, the balanced growth hypothesis suggests that individual plant tissues should provide a ‘balanced internal economy’ as each component supplies resources for the other [@davidson1969effect]. This functional equilibrium between tissues can then be adaptive if conditions limit *A~n~* or soil nutrient uptake [@cannell1985attributes], such that plants should allocate resources to the organ that is capturing the resource most limiting growth [@shipley2002balanced]. Changes in plant resource allocation is also theorized to be a function of allometric trajectories of plant development related to plant size, independent of changes in nutrient supply [@muller2000effect]. In this strategy, investment into leaf mass increases with both stems and root, but not proportionally, as a greater allocation of biomass to the stem exists as a simple function of plant size [@zens2002sizing]. When constrained by ontogeny, plants are more likely to adjust tissue morphology, chemistry, metabolism or turnover to alter resource capture [@reich2002root]. 

\
*Tree canopy resource gradients*

\
Incident PPFD declines exponentially with cumulative leaf area index from the top of the tree downward, creating steep light gradients within tree canopies [@monsi2005factor]. Leaf photosynthesis responds strongly and non-linearly to irradiance [@evans1995carbon]. As costs and limitations of light harvesting prevent plants from exposing all leaves to full sun [@niinemets2010review], it follows that a substantial portion of canopy C assimilation should occur in leaves with the highest exposure to light. Consequently, the distributions of resources required for *A~n~* are partially defined by canopy light gradients. As the photosynthetic capacity of leaves is related to its N content [@field1986photosynthesis], a larger investment in N to the upper canopy should yield a larger return from whole canopy C assimilation [@ellsworth1993canopy]. The supply of water also imposes limits photosynthetic C gain through direct limitations on leaf level physiology. The stomatal resistance to CO~2~ uptake is a function of the balance between transpiration losses and leaf water potentials [@farquhar1982stomatal] and sun leaves frequently experience greater water limitations in the upper canopy [@sellin2008effects; @niinemets2012optimization]. Thus, photosynthetic N investment in the upper canopy will be ineffective in enhancing *A~n~* if water supply is insufficient [@niinemets2012optimization; @peltoniemi2012co]. Overall, the allocation of soil resources within the canopy constrains leaf physiology and photosynthetic capacity, thereby regulating the efficiency of CO~2~ uptake.    

\
*Fate of assimilated carbon*

\
Carbon allocation represents the fraction of net primary productivity distributed to different tissue components above and belowground. In trees, C allocation encompasses investment into tissue biomass production as well as fluxes including respiration, exudation and turnover rates [@litton2007carbon]. The fate of this assimilated C is regulated by the delicate balance between leaf C uptake (source) and the C sink strength of the different biomass pools. For example, the sensitivity of C source and sink activities to water and nutrient availability could lead to an imbalance between C supply and C used for tissue growth and respiration [@fatichi2014moving]. Additionally, imbalances between source and sink activity can lead to investment into carbohydrates synthesis as a transient C storage sink [@paul2001sink].
\
As woody plants have competing tissue carbohydrate sinks, growth should principally depend on the allocation of leaf C assimilate among different sink organs [@kozlowski1992carbohydrate; @lacointe2000carbon]. In response to changing environnmental conditions, however, trees may adaptively shift tissue C allocation to balance growth, storage and C loss. Due to conservation of mass, it is theoretically possible to track the fates of this assimilate from leaf C uptake to their eventual destination in above and belowground pools. Although mass balance approaches can be used to quantitatively asses tree C allocation, few studies so far have been able to provide direct empirical measurements of C allocation among component pools [@klein2015].

\
*Eucalyptus tree species as model for research*

\
Research on *Eucalyptus* trees is ecologically important for Australia as it is the most dominant tree genus [@boland2006forest]. *Eucalyptus* forests are the continent’s most common forest type, covering about three-quarters of Australia’s native forests (92 million hectares) and occurring in all but the continent’s driest regions [@ASOFR2013]. *Eucalyptus* tree species are also economically important globally as they are commonly cultivated in plantations due to fast growth. Despite the fact that only a few *Eucalyptus* species have natural ranges outside continental Australia [@pryor1981eucalyptus], *Eucalyptus* trees are grown in plantations in over 90 countries [@booth2013eucalypt]. This is because *Eucalyptus* species have been shown to exhibit both adaptive plasticity and genetic specialization to spatial variation in climate [@byrne2013adaptation]. Currently, the global plantation area of eucalypts totals nearly 20 million hectares, accounting for around 15 % of the world’s total plantation forests [@IUFRO2015]. Consequently, this iconic Australian tree species is an excellent model to investigate strategies of resource allocation in trees facing global climate change.

### Current Knowledge Gaps

\
*Resource allocation in trees*

\
The distribution of assimilated C is a primary determinant of plant growth [@friedlingstein1999toward], yet our knowledge of the mechanisms by which allocation is regulated is poor [@poorter2012biomass].  A key issue with drawing generalized conclusions about the plasticity of C allocation in trees is with the inconsistency in terminology used to define C allocation to specific tissue or ecosystem components [@litton2007carbon]. Biomass partitioning should not be confused with the allocation of newly fixed photosynthates to different organs, as the measured biomass at any time point represent the cumulative result of dynamic C allocation over time [@poorter2015does]. This dynamic C allocation includes not only plant parts such as leaves, stems and roots but also respiration, exudation, turnover and transient C storage pools. As C allocation integrates all of these processes, it is extremely difficult using current methods to assess C allocation in whole trees. Disentangling the effects of resource supply on shifts in C allocation is often assessed in plants across “snapshots” in time, which should be done with caution [@reich2002root]. This is because of plants have developmental shifts in biomass partitioning, independent of resource supply, as they age [@muller2000effect; @poorter2015does].  Additionally, supplies of light and soil resources fluctuate continuously, making equilibrium with allocation at any “snapshot” highly unlikely [@shipley2002balanced].

\
The allocation of photosynthetic C above and belowground is an important factor in terrestrial C cycling, yet our understanding of how global change impacts C allocation is incomplete [@litton2007carbon; @warren2012timing]. As accurately measuring tree C allocation remains a difficult task, especially belowground, drawing conclusions that are applicable to whole plants or ecosystems remains a challenge. Currently, the representation of C allocation lags behind photosynthesis (*A~n~*) in process-based forest models [@friedlingstein1999toward; @franklin2012modeling; @iversen2014terrestrial]. This lack of understanding of C allocation in trees is of major concern due to the potential for forest ecosystems to sequester C in a changing climate. This deficiency requires more empirical data to derive basic principles that drive patterns of tree C allocation in changing environments. However, this will require novel experiments and approaches to better quantify shifts in C allocation above and belowground in future studies. 

\
*Coupling of photosynthesis and tree growth*

\
On short timescales, *A~n~* and respiratory losses may not correlate with growth because of tissue C storage pools. On longer timescales, however, they determine net plant C balance and must correlate to growth. This had led to the long standing debate over how strongly plant growth is controlled by either source or sink activity [@sweet1966role; @korner2013growth]. Studies manipulating either source activity (CO~2~ fumigation or defoliation) or sink activity (fruit removal, girdling or low growth temperatures) have not reached consensus when addressing this debate. This uncertainty arises from the difficulty in measuring the balance between C uptake and the fate of assimilated C among pools with long (biomass) or short (carbohydrate storage, respiration, exudation) retention times. When shifts in carbohydrate storage, tissue respiration or turnover rates occur, rates of C assimilation may not correlate with biomass production at a given time point [@rocha2006linking; @litton2007carbon; @gough2008multi]. To assess this balance will likely require integration of empirical and modelling approaches to assess leaf physiological and whole plant responses to manipulations of source-sink activity. To address this knowledge gap, new approaches are needed to test how interactions between source and sink activity affect the fate of assimilate C across different temporal scales. 

\
*Within canopy resource utilization*

\
Leaf photosynthesis has a saturating response with light and N is highly correlated with photosynthetic capacity. Consequently, it is commonly assumed that a limited availability of N should be distributed proportional to light availability within tree canopies. Observed canopy distribution of N is often less steep than optimal theory suggests, however, with shade leaves having more N than expected based on average light gradients [@peltoniemi2012co]. Additionally, constraints on water distribution from the soil to the upper canopy may negatively impact the distribution of photosynthetic N to canopy light availability [@niinemets2012optimization; @peltoniemi2012co]. Whether insufficient hydraulic supply results in the observed sub-optimal canopy N gradients has yet to be empirically tested. Assessing leaf C gain as a function of light availability is also made difficult by frequent light fluctuations within a canopy, via sunflecks. Sunflecks cause temporal variation in PPFD that is not taken into account when considering what is optimal for a plant in terms of distributing resources along a gradient of light availability.

\
Leaves have been proposed to exhibit optimal physiological behavior in order to efficiently utilize and transport resources to maximize *A~n~* [@thornley1972model]. In trees, leaf physiology often focuses on full sun leaves and relationships between leaf physiological behavior and the availability of N, water and light between sun and shade leaves requires further attention. For example, g~s~ has been hypothesized to be distributed within a canopy to utilize supplies of light, N and water to maximize *A~n~* [@peltoniemi2012co]. In shade leaves, stomata might be expected to be more closed to efficiently use water with generally low *A~n~*. To date, however, no clear picture has emerged on the relationship between g~s~ and *A~n~* within canopies [see @jifon2003moderate; @tissue2006spatial; @sellin2010variation]. As mesophyll conductance (g~m~) also limits *A~n~*, complex relationships may exist between canopy light gradients, leaf N and g~m~. Unfortunately, a scarcity of values for g~m~ within tree canopies [see @lloyd1992low; @warren2003transfer; @piel2002effect; @warren2007internal] hinders our ability to relate individual leaf physiological behavior to optimal canopy C uptake. As the CO~2~ drawdown from the atmosphere to the site of carboxylation includes g~s~ and g~m~, relationships between *A~n~* with light availability, N and water within canopies will require the integration of both physiological parameters in future experiments.

### Thesis Objectives
The overall research goal is to evaluate how trees adjust their growth and physiology to maximize resource uptake and C gain. Specifically, this PhD research addresses knowledge gaps of how tissue C allocation, source and sink regulation and resource distribution affect the coordination between *A~n~* and whole tree growth. In order to investigate key mechanisms that drive patterns in resource allocation in trees this research was carried out across multiples scales, from leaf isotope discrimination across the photosynthetic CO~2~ flux pathway to tissue specific biomass partitioning to total belowground C allocation. Understanding how resource allocation is correlated with individual leaf physiological behavior within tree canopies is crucial in accurately determining the capacity for whole canopy C assimilation, which is the essential resource for tree growth.  Aspects of this research use manipulations of key global change factors, including elevated CO~2~, warming and drought to investigate the plasticity of observed physiological and growth responses to future climate scenarios. An improved understanding of how C is allocated within trees will supply much needed empirical data for process-based forest models where C allocation is currently poorly represented. 

\
This research focuses on two Australian tree species, *Eucalyptus tereticornis* and *Eucalyptus saligna*, which have important roles in both native forests ecosystems and as commercial plantation timber. *Eucalyptus tereticornis* is part of the critically endangered Cumberland Plain ecological community and *Eucalyptus saligna* is part of the critically endangered Blue Gum High Forest ecological community, with both communites having fragmented geographic distributions in the Sydney Basin bioregion [@hughes2011web]. Both of these species are part of the “big nine” *Eucalyptus* species group which accounts for more than 90 % of planted *Eucalyptus* forests worldwide [@stanturf2013eucalyptus]. As a result, the core findings of this PhD research have both conservation and commercial applications in addressing the productivity of these two important tree species in the face of global climate change. For example, considerable uncertainty remains as to the magnitude of CO~2~ fertilization on this continent as much of the vegetation is already under nutrient and/or water limitation [@hughes2003climate]. 

\
This research was conducted using the state of the art Whole Tree Chamber experiment as well as a novel field-based seedlings container study at Western Sydney University. Using the two *Eucalyptus* tree species, fundamental principles of common optimization theories were tested at several tree growth stages. Leaf based data were combined with tissue biomass production and canopy C fluxes to develop a better understanding of how resources are allocated to optimize whole tree growth. Empirical data were also integrated with a seedling growth model to test how resource limitation impacts the coordination between A and growth. Specifically, this thesis aimed to address current knowledge gaps by answering the following main questions:

\
1.	**Where does the carbon go?** 
\
How will biomass partitioning and carbon allocation in *Eucalyptus* trees be affected by global climate change and belowground resource limitation?

\
2.**When do photosynthesis and growth not add up?**
\
What do mass balance approaches reveal about the coordination of growth and photosynthesis at different temporal scales?

\
3.	**Are whole canopies optimized for carbon gain?**
\
How does resource availability within *Eucalyptus* tree canopies interact with dynamic physiology of sun and shade leaves to maximize canopy carbon gain?

### Thesis Outline

**Chapter 2** was designed to address thesis questions 1 & 2 by manipulating belowground sink strength in *Eucalyptus tereticornis* seedlings, via a range of container sizes, in a novel field-based experimental design. The effects of belowground resource limitation were then used to investigate patterns in biomass partitioning, leaf gas exchange and growth between container treatments and field grown seedlings. Empirically measured gas exchange parameters were then used to model daily C gain for each seedling to test the coordination between the reduction in *A~n~* and biomass production of seedlings with soil volume restriction. The sensitivity of this model to different C allocation scenarios was used to speculate possible fates of photosynthetic C not accounted for in the default model. Results of this study are then used to address the ongoing debate over source or sink controls of *A~n~* and growth. The flexibility of this mass balance modelling approach is used to highlight the importance of quantifying C allocation when evaluating the impacts of resource limitation on tree seedling growth.

\
**Chapter 3** addressed thesis question 3 by combining leaf gas exchange with online C isotope discrimination to measure the responses of sun and shade leaf physiology to light availability. The distribution of leaf N and leaf hydraulic conductance within *Eucalyptus tereticornis* canopies where examined to test if the resources required for *A~n~* were preferentially invested into sun leaves, as predicted by standard optimal theory, to maximize whole canopy C gain. The physiological capacity of shade leaves to respond to increases in light availability was quantified to determine if shade leaves “lie in wait” for sunflecks. Trees were grown in climate controlled WTCs under ambient and elevated air (+3&deg;C) temperature treatments to test the impacts of future climate warming on each of these processes. Rarely have relationships between *A~n~* and both g~s~ and g~m~ been quantified within tree canopies, thus results from this experiment are used to reveal potential new mechanisms underpinning leaf gas exchange responses to light. Unexpected decreases in water-use efficiency in shade leaves where related to the capacity of inner canopy leaves to rapdily utilize sunflecks. Empirical data from this experiment improve our ability to predict whole canopy C gain by prioritizing both sun and shade leaf physiology, which may be optimized differently.

\
**Chapter 4** addresses thesis questions 1 & 2 by quantifying high resolution net canopy photosynthesis measurements and C allocation in *Eucalyptus saligna* trees grown under interacting drought and elevated CO~2~ treatments. The unique WTC experimental design measures cumulative net aboveground C fluxes which were compared to canopy leaf area and tree biomass production. A novel framework was also applied to calculate a more reliable estimate of the sensitivity of TBCA to global climate change. I then evaluated how interacting climate change factors impacted C allocation to above and bewloground pools through time. Results from this experiment emphasize the need to correctly define individual aspects of tree C allocation and separate impacts on measured biomass from other components of C allocation when evaluating tree growth responses. As empirical measurements of C allocation are difficult to obtain, especially with belowground processes, these results provide much needed empirical data to validate process-based model where C allocation is represented. 

\
**Chapter 5** presents the synthesis and outlook of the major findings in my PhD research as they relate to each main thesis question. First, shifts in C allocation likely occurred as these two *Eucalyptus* species were impacted by changing environments, even though biomass partitioning of harvested trees remained relatively conserved. Combined results from Chapters 2 & 4 are used to discuss how observed responses of biomass partitioning and C allocation correspond to prevailing theory and how these mass balance approaches have improved our understanding of the investment of photosynthetic C in trees. Second, I show that coupling between total C gain and tree growth can be disrupted over shorter experimental time frames, while over longer time scales they are strongly correlated as a function of leaf area. Results from Chapter 2 use empirical data and modelling approaches to address the current debate over source and sink control over seedling growth, while Chapter 4 is used to discussed how unique measurements of net canopy photosynthesis correlate to tree productivity under future climate scenarios. Last, I show that sun and shade leaves exhibit different physiological behavior in order to utilize differential availability of external resources within *Eucalyptus tereticornis* canopies. Results from Chapter 3 are used to show that shade leaf physiology is likely optimized differently from sun leaves in order to respond to sunflecks, which has important consequence for current theories regarding how resources are allocated to optimize canopy C gain.

# 5.1 Synthesis
It has long been recognized that resources limit plant growth in different environments, at different life stages and individual plant processes are limited by different resources [@bazzaz2000reproductive]. Consequently, a quantitative understanding of how plants gain and allocate resources is necessary to predict their success in any environment [@mooney1972carbon]. In this thesis work, resources allocated for growth in *Eucalyptus* tree species are classified into two distinct groups. The first group consists of environmental plant resources that are captured, distributed and utilized to drive rates of A and thus tree C gain. These C assimilates comprise the second group, which are the essential internal resource required to fuel tissue growth, storage and respiration. These two resource group are inextricably linked and interact to define plant growth across spatial and temporal scales. For example, the C expended in acquiring N makes up a significant fraction of the total energy a plant consumes, while leaf N investment constrains photosynthetic capacity [@chapin1987plant]. In trees, rates of A will then depend on the photosynthetic light response of individual leaves and the energetic trade-offs of gas exchange related to transpiration and water supply [@givnish1988adaptation].

\
The research presented in this thesis was designed to investigate resource allocation in trees at individual tissue and whole plant scales using model *Eucalyptus* species. I sought to address theories of plant functional balance by testing biomass partitioning in seedlings and trees undergoing various environmental manipulations. As observed biomass production may not necessarily reveal shifts in plant functional responses, I evaluated the sensitivity of the allocation of photosynthate above and belowground across different temporal scales. Using mass balance approaches I then tested the coordination between growth an net leaf photosynthesis (*A~n~*), using leaf gas exchange parameters in seedlings and measurements of net canopy C gain in trees. To help bridge the knowledge gap between leaf and canopy C gain I investigated the distribution of soil resources as a function of light availability within canopies and the effect this has on individual leaf physiology. By utilizing novel experimental approaches, evidence from this work improves our understanding of functional processes that determine the net C uptake of trees and then how this assimilated C is used to fuel growth. The contribution of this body of work provides fundamental evidence underlying resource allocation in ecologically and commercially important Eucalyptus tree species.

###5.1.1 Where does the carbon go?
This thesis question arises from large uncertainties that remain regarding fundamental processes which affect terrestrial C cycling.  The question “Where does the carbon go?” arises from the need to track the fate of C from canopy *A~n~* to determine the contribution of forests ecosystems to C cycling [@litton2007carbon]. Currently, empirical data regarding this topic are critical to the development of C allocation in forest models and subsequent predictions of global C balance under climate change [@franklin2012modeling]. Growth responses during early phases of trees establishment (seedlings or young trees) to changes in soil resource availability or climate change factors will likely depend on the ability to maintain positive C balance between growth, respiration and storage. Consequently, understanding environmentally driven shifts in C allocation in young *Eucalyptus* trees will be crucial to manage their fitness in fragile native ecosystems and their productivity in terms of timber production and quality in agroforestry systems.

\
First, I examined patterns in biomass partitioning of *E.tereticornis* seedlings with belowground resource limitation (Chapter 1) and with *E.saligna* trees exposed to eC~a~ and drought treatments (Chapter 2).  Across these studies, partitioning of harvested biomass appeared to follow allometric trajectories related to overall plant size, regardless of treatment manipulation. Partitioning to roots, leaves and stems in *E.tereticornis* seedlings was conserved across a large variation in seedling biomass with and without soil volume restriction (15-175 g). During this early growth stage, these results infer that growth inhibition from reduced belowground sink strength did not elicit a functional partitioning response. With much larger 2 year old *E.Saligna* trees, grown in WTCs, differences in partitioning to stem biomass were detected between aC~a~ and eC~a~ treatments.  These patterns were also attributed to size dependent relationship associated with ontogeny [see @poorter2015does], rather than a functional tree response to eC~a~.

\
Combined results from these two experiments argue against traditional views of plant functional balance in the context of observed biomass production. These theories posit that plants will “optimally forage” for the most limiting resource, thus shifts in biomass partitioning should occur. However, adaptive plant responses can extend beyond biomass production at any given “snapshot” in time.  This makes tracking C allocation to processes other than observed biomass just as important in assessing growth responses. Here, empirical and modelling evidence from Chapters 2 & 4 reveal that detection in shifts of tissue C allocation were necessary to interpret whole tree response to environmental manipulations. For *E.tereticornis* seedlings, modelling results infer that increases in C allocation to pools other than biomass were required to fully explain the effects of soil volume restriction on seedling growth. For *E.saligna* trees, increased leaf C demand under eC~a~ treatments resulted in higher C allocation to leaves without altering observed leaf biomass production. Overall, the ability to distinguish biomass production from C allocation across tissues reveals that alternate explanations are likely need to interpret the degree in which trees strive to maintain functional balance.

\
Alternatively, shifts in tissue morphology, metabolism or turnover to alter resource uptake of loss [@reich2002root], increased root exudation to alleviate resource limitation [@phillips2011enhanced] or increased C allocation to storage [@sala2012carbon ; @dietze2014nonstructural] may be used to balance trade-offs between tissue sink strength, resource availability and source C supply. Partial evidence for these ‘non-biomass’ responses were evident in *E.tereticornis* seedlings during this thesis research.  Increases in specific root length were detected in some, but not all, of seedlings with soil volume restriction. Modelling results also revealed that increases in tissue respiration rates were a possible mechanism to account for the oversupply of C not allocated to biomass. Increases in leaf carbohydrate storage were correlated with reduced belowground sink strength in these seedlings, and it is possible that C storage could also have increased in other tissues. Root exudation may have increased in response to adverse poor quality soil conditions with *E.tereticornis* seedlings in containers or in *E.saligna* trees under eC~a~ to meet resource demand, but was not explicitly measured.

\
The ability to compare biomass partitioning with aspects of C allocation across multiple experiments highlights how partial accounting of C may lead to erroneous conclusions regarding adaptive plant responses to changing environments. Overall, these results reveal why studies using only biomass partitioning to assess functional balance or allometric based theories have mixed results.  Additionally, shifts in above but not belowground C allocation *E.saligna* trees disagrees with the regularity of enhancement of belowground processes in other trees species under eC~a~ [see @palmroth2006aboveground; @iversen2014terrestrial]. Shipley et al. [-@shipley2002balanced] states that it is more appropriate to say that plants shift biomass allocation to reduce imbalances between leaf source activity and tissue resource acquisition. Collectively, results from this research tend to agree with this conclusion, with the caveat that the concept of allocation must be extended to include fates of C other than measured biomass. Consequently, we agree with Poorter et al. [-@poorter2012biomass] that understanding C allocation above and belowground requires a better understanding of the interactions between tissue source and sink activity at any time point. In order to fully understand the impact environmental change has on forest productivity approaches to quantify patterns in C allocation must be prioritized in future studies.

###5.1.2 When do photosynthesis and growth not add up?

This thesis question addresses the debate over how strongly plant growth is controlled by either source or sink activity, which may disrupt the coordination between A and growth at different temporal scales. Carbon assimilate is first partitioned to provide sufficient sucrose for the immediate demands of the plant during the day, and sufficient starch to meet ‘anticipated’ demands during the following night [@smith2007coordination]. The C demands for each tissue, referred to as tissue C sinks, determine the C budget for the entire plant and regulate C allocation. Despite competition among highly integrated C sinks, woody plants also maintain storage carbohydrate pools as C reserves [@kozlowski1992carbohydrate]. Understanding the coordination between plant growth and *A~n~* thus requires mass balance approaches to quantify the fractions of C supply allocated to growth, storage and respiration of different organs. Reductions in tissue sink strength have been shown to signal the down regulation of *A~n~*, which can led to increased starch synthesis for storage [@sage1994acclimation; @kitao2007interaction]. This had led to support for the argument that increased shifts to C storage will compete with C available for plant growth [@chapin1990ecology], which may then disrupt the coordination between *A~n~* and growth.

\
To address this thesis question the belowground sink strength of *E.tereticornis* seedlings was manipulated, through container size treatments, to test the effects of sink limitation on *A~n~* and leaf TNC production (Chapter 1). Empirical results and modelling approaches were combined to test the coordination of A and growth of seedlings with and without soil volume limitation over 120 days. First, apparent reductions in belowground sink strength negatively impacted leaf N content and photosynthetic capacity, while leaf starch increased. These results support other findings where manipulation of tissue C sinks leads to carbohydrate accumulation and photosynthetic down regulation [@hoch2002altitudinal; @iglesias2002regulation; @equiza2006photosynthetic; @urban2007girdling; @haouari2013fruit]. Second, large reductions of harvested biomass in seedlings with soil volume limitation initially suggested that observed reductions in *A~n~* and growth were tightly linked.  As previously shown in thesis question 1, however, inadequate accounting of C allocation could lead to premature conclusions regarding this linkage. Importantly, using measured reductions in *A~n~* with a mass balance seedling growth model largely over-predicted biomass production from observed results. These findings reveal that not only can *A~n~* and growth not add up when belowground sink strength changes but other mechanisms, beyond *A~n~* and carbohydrate accumulation, must now be explored to explain growth responses.

\
At long enough time scales, however, A and respiratory losses together determine net C balance and must be coordinated to plant growth. Consequently, we need to evaluate if trade-offs between storage and growth actually matter for long term C balance of trees [@palacio2014does]. The difficulty in measuring total canopy C uptake and the allocation of this assimilate to different tissue sinks currently impedes the ability to quantify whole tree C balance through time. Combining allometric approaches to estimate growth with seasonal variation in carbohydrates of stem wood and roots, Genet et al. [-@genet2010age] found contrasting results with the C balance between storage and growth across a chronosequence of stand age. Utilizing the novel WTC experimental design, I sought to address this knowledge gap by applying a simple mass balance approach with *E.saligna* trees (Chapter 4). Empirical measurements of net cumulative C uptake were correlated with whole tree C mass, which integrates the total allocation of C to growth and storage over an 11 month period.  This simplified method allows for the coordination of *A~n~* and growth to be tested without issues in accounting for C retention in tissues through time [@litton2007carbon]. During this time period, total tree C mass was strongly correlated to net canopy photosynthetic C gain across a 2.5 fold range in tree size. If the C balance between growth and storage was disrupted by eC~a~ or drought in these trees, it did not affect the overall coordination between C supply and growth over ~1 yr. Overall, results from Chapters 2 & 4 highlight how utilization of C mass balance improves our ability to explore mechanisms in which source and sink activity feedback to tree growth. Although I show that answers to the debate regarding the coordination of allocation of C to storage and growth requires a deeper understanding C allocation, it appears that whole canopy assimilation and tree growth are tightly coordinated over long periods.

###5.1.3. Are whole canopies optimized for carbon gain?

Scaling from single leaf photosynthetic performance to net canopy assimilation is difficult because of concomitant variations in environment and foliage physiology and structure [@niinemets2009packing]. The ability to estimate whole canopy C gain involves knowledge of the non-linear responses of A to light between shaded and sunlit leaves [@de1997simple; @linderson2012up], which requires the ability to differentiate  light energy utilization, environmental resource distribution, physiological behavior and CO~2~ fluxes  within tree canopies [@dai2004two; @peltoniemi2012co; @niinemets2012optimization]. Theory suggests that interactions between traits which influence *A~n~* and transpiration should interact to determine optimal patterns of behavior for whole plant C gain [@givnish1988adaptation].  Theories of optimal resource allocation and leaf physiological behavior have been developed [@cowan1977stomatal; @medlyn2011reconciling; @peltoniemi2012co] and subsequently tested [@wright2003least; @heroult2013optimal; @prentice2014balancing; @lin2015optimal] across different ecosystems and plant functional types. This thesis question arises because optimal leaf physiology is commonly assessed for seedlings or ‘full sun’ leaves, thus our understanding of how resource allocation and individual leaf physiology interact to maximize net canopy C uptake is surprisingly limited. Seeking answers to ecological questions such as “Where does the carbon go?” and “When do photosynthesis and growth not add up?” first requires an understanding of how leaves in different light environments utilize resources to maximize canopy C gain.

\
Theories of leaf economic strategies are often used to describe the patterns in which resources are distributed in order for plants to optimize *A~n~* [@wright2003least].  In this economic framework, I first evaluated how N and water supply were distributed in relation to *A~n~* within *Eucalyptus tereticornis* tree canopies (Chapter 3). Leaf N and photosynthetic capacity were found to be highest in full sun leaves, which agree with conventional theory that resources for A should be preferentially invested relative to light availability. Overall, higher measured rates of *A~n~* in full sun leaves compared to shade leaves implies that N resources were invested to maximize source activity in upper canopy full sun leaves. The distribution of leaf hydraulic conductance, however, was not correlated with canopy N gradients or *A~n~* between sun and shade leaves. It was therefore necessary to further investigate relationships between leaf physiology, carbon uptake and water-use efficiency (WUE) across leaf types.

\
It has been previously hypothesized that stomatal conductance (g~s~) should be distributed within a canopy to utilize supplies of light, N and water to maximize *A~n~* [@peltoniemi2012co]. Under ambient light conditions g~s~ was consistently higher in shade leaves despite lower rates of *A~n~*. The resultant inefficient water use in shade leaves suggests that stomatal behavior may be optimized differently within tree canopies. Pearcy and Way [-@pearcy2012two] theorize that shade leaves may have mechanisms to enhance sunfleck use, including changes in induction through enzyme regulation or stomatal opening. Our data agree with Tausz et al. [-@tausz2005dynamic] that sustaining higher g~s~ may be a strategy to efficiently utilize sunflecks through reduced stomatal response time. This strategy, however, does not guarantee increased leaf C uptake as mesophyll conductance (g~m~) may  still limit *A~n~*.  Under high light conditions g~m~ and *A~n~* responded rapidly in shade leaves, leading to leaf C gain of greater magnitude than sun leaves. Rarely have relationships between *A~n~* and both g~s~ and g~m~ been quantified within tree canopies, thus I reveal a possible new mechanism of how leaf physiological behavior responds to light. These findings show that resources may also be distributed within a canopy to utilize sunflecks and that both CO~2~ resistance pathways must be accounted for when evaluating leaf behavior to optimize canopy C gain.

###5.2 Conclusions
The diversity and non-linearity of plant ecophysiological processes poses challenges in predicting and analyzing structure and function of ecological systems [@field1983allocating]. These processes include complex strategies in ways plant uptake, distribute and utilize resources for growth in fluctuating environments. I examined how these resources, in the context of external environmental resources and new C assimilate, are allocated to fuel growth in both current and future climate conditions. This thesis work demonstrates that quantifying the underlying processes defining tree growth requires knowledge of the feedbacks between leaf source activity and tissue sink strength, which are both constrained by resource availability.  When addressing the fates of assimilated C across multiple experiments it was determined that biomass partitioning patterns did not support theories of “optimal foraging” when faced with eC~a~, drought, or belowground resource limitation. If trees strive to maintain functional balance, this collective research indicates that quantifying shifts in C allocation beyond biomass production are the key to unraveling adaptive responses. Additionally, I show how measuring shifts in C allocation are now necessary to gain new perspective regarding sink and source controls of growth and *A~n~*. This thesis research advocates for continued use of C mass balance approaches which include empirically measured or accurately modeled whole plant net C uptake. As this research presents new strategies in which tree canopies are optimized for C gain, further investigation of resource allocation and leaf physiological behavior within canopies should be prioritized to advance predictions of tree C gain. It will be the ability to quantify cumulative plant C gain through time combined with continued exploration of the fate of assimilated C that will allow future research to elucidate plant responses to environmental change beyond “snapshots” in time.

###5.2.1 *Eucalyptus* forests
A goal of this thesis was to contribute to the knowledge of the physiological ecology of *Eucalyptus* tree species to aid in understanding the susceptibility of threatened native forest ecosystems and the productivity of commercially important tree species to future climate change. First, findings related to the response of shade leaf physiology to dynamic light environments contributes to the overall understanding of canopy C gain in *Eucalyptus* trees. This utilization of sunflecks may play a critical role in productivity of *Eucalyptus* open-forests, specifically dry sclerophyll forests, in Australian ecosystems. Canopy cover in these open forest types likely allow for frequent sunflecks of high intensity at varying lengths.  Additionally, many *Eucalyptus* species are characterized by steep leaf angles which can alter light penetrating the canopy, leaf physiology, radiation loads and C gain [@cowan1981coping; @king1997functional; @james2000leaf; @falster2003leaf ]. Integration of these research findings with the functional role of leaf orientation may explain how *Eucalyptus* trees maintain positive C and energy balance in resource poor ecosystems and may be applicable to improve commercial stand productivity through thinning or pruning.

\
Second, aspects of leaf physiology and C allocation in these *Eucalyptus* trees species were less sensitivity to manipulations of warming, eC~a~ and drought than hypothesized. *Eucalyptus* trees are often characterized as being highly adaptable in order to cope with Australia’s prevailing climate and soils. It is possible that this adaptability plays a role in the observed stability of ecophysiological processes across the duration of these experiments (months to years). Consequently, warming treatments and simulated droughts may not have been of great enough magnitude to elicit functional plant response within experimental time frames. However, these results should by no means be used to conclude that Australian forest ecosystems are overly resilient to future climate regimes.  Future climate scenarios predict increased frequency of extreme daily temperatures, heat waves, and limited water resources due to higher temperature and decreased rainfall in Australia [@ipcc2014]. Importantly, this research emphasizes that further empirical data quantifying C allocation to specific tissue, flux and ecosystem pools are critical in uncovering the drivers of tree responses to climate. Continued investigation of the cumulative impacts of eC~a~, warming and drought on *Eucalyptus* tree growth and fitness, such as the WTC experiments, will develop our ability to predict ‘tipping points’ for Australian forest ecosystems under future climate change.


# References {.unnumbered}
