
\documentclass[a4paper]{article}

%--- Load packages. 
\usepackage{amssymb}
\usepackage{amsmath}
\usepackage{framed}
%\usepackage{textcomp}

\pagestyle{empty}

% avoid ugly indentation of paragraphs
\usepackage{parskip}
\usepackage{graphicx}

% open sans font
%\usepackage[default,osfigures,scale=0.9]{opensans}
\usepackage{newtxtext}
\usepackage{newtxmath}


% subfolder with the figures (within manuscript/)
\graphicspath{ {./figures/} }

% for author affiliations
\usepackage{authblk}

%allows inline citations
\usepackage[round]{natbib}
\bibliographystyle{plainnat}

% for degree symbol
\usepackage{gensymb}

% for line numbers
\usepackage{lineno}

% margin size
\usepackage{geometry}
\geometry{verbose,tmargin=3cm,bmargin=3cm,lmargin=3cm,rmargin=3cm}

% for bibtex
% \usepackage{authordate1-4}
% \bibliographystyle{authordate1}

%allows subscripts in text mode
\usepackage{fixltx2e}

%allows rotation of table??
\usepackage{rotating} 

%allows alignment of caption to the left
\usepackage{caption} 
\captionsetup[table]{singlelinecheck=false}

%allows not italic greek letters
\usepackage{textgreek}

\begin{document}

%------------------------------------------------------------------------------------------%

<<preload, echo=FALSE>>=
library(knitr)
opts_chunk$set(echo=FALSE)
@


%--------------------------------------------------------------------------------------------%

<<echo=FALSE, message=FALSE, warning=FALSE>>=
library(xtable)


phys_data <- read.csv("pdfs/pve_table2.csv")
colnames(phys_data) <- c("Volume~(L)", 
                        "\\textit{A}\\textsubscript{max}", 
                        "\\textit{R}\\textsubscript{dark}",
                        "\\textit{J}\\textsubscript{max}",
                        "\\textit{Vc}\\textsubscript{max}",
                        "\\textit{g}\\textsubscript{s}",
                        "\\textit{g}\\textsubscript{1}")

@


%seedling data table


<<results='asis'>>=
phystab <- xtable(phys_data, label="table:Table2",caption="Responses of leaf level gas exchange parameters ")

print(phystab, include.rownames=FALSE,sanitize.colnames.function=function(x){x},
      floating.environment='sidewaystable',caption.placement="top",
       hline.after = getOption("xtable.hline.after", c(-1,0,7,nrow(phystab))))
@




%--------------------------------------------------------------------------------------------%


-------------------------------------------------------------------------%
\end{document}

